// generated by dbgen ; DO NOT EDIT

package main

import (
	"time"
)

//
// found DBObject generator
//
func (o found) NewObj() interface{} {
	return new(found)
}

//
// found DBObject interface functions
//
func (o *found) InsertValues() []interface{} {
	return []interface{}{o.ID, o.Kind, o.Name, o.Note}
}

func (o *found) UpdateValues() []interface{} {
	return []interface{}{o.ID, o.Kind, o.Name, o.Note}
}

func (o *found) MemberPointers() []interface{} {
	return []interface{}{&o.ID, &o.Kind, &o.Name, &o.Note}
}

func (o *found) Key() int64 {
	return 0
}

func (o *found) SetID(id int64) {
}

func (o *found) TableName() string {
	return ""
}

func (o *found) SelectFields() string {
	return "id,kind,name,note"
}

func (o *found) InsertFields() string {
	return "id,kind,name,note"
}

func (o *found) KeyField() string {
	return ""
}

func (o *found) KeyName() string {
	return ""
}

func (o *found) Names() []string {
	return []string{"ID", "Kind", "Name", "Note"}
}

func (o *found) ModifiedBy(user int64, t time.Time) {
}

//
// summary DBObject generator
//
func (o summary) NewObj() interface{} {
	return new(summary)
}

//
// summary DBObject interface functions
//
func (o *summary) InsertValues() []interface{} {
	return []interface{}{o.Site, o.Servers, o.VMs}
}

func (o *summary) UpdateValues() []interface{} {
	return []interface{}{o.Site, o.Servers, o.VMs, o.ID}
}

func (o *summary) MemberPointers() []interface{} {
	return []interface{}{&o.ID, &o.Site, &o.Servers, &o.VMs}
}

func (o *summary) Key() int64 {
	return o.ID
}

func (o *summary) SetID(id int64) {
	o.ID = id
}

func (o *summary) TableName() string {
	return "summary"
}

func (o *summary) SelectFields() string {
	return "sti,site,servers,vms"
}

func (o *summary) InsertFields() string {
	return "sti,site,servers,vms"
}

func (o *summary) KeyField() string {
	return "sti"
}

func (o *summary) KeyName() string {
	return "ID"
}

func (o *summary) Names() []string {
	return []string{"Site", "Servers", "VMs"}
}

func (o *summary) ModifiedBy(user int64, t time.Time) {
}

//
// user DBObject generator
//
func (o user) NewObj() interface{} {
	return new(user)
}

//
// user DBObject interface functions
//
func (o *user) InsertValues() []interface{} {
	return []interface{}{o.First, o.Last, o.APIKey, o.Level, o.Local, o.Email}
}

func (o *user) UpdateValues() []interface{} {
	return []interface{}{o.First, o.Last, o.APIKey, o.Level, o.Local, o.Email, o.USR}
}

func (o *user) MemberPointers() []interface{} {
	return []interface{}{&o.USR, &o.First, &o.Last, &o.APIKey, &o.Level, &o.Local, &o.Email}
}

func (o *user) Key() int64 {
	return o.USR
}

func (o *user) SetID(id int64) {
	o.USR = id
}

func (o *user) TableName() string {
	return "users_view"
}

func (o *user) SelectFields() string {
	return "usr,firstname,lastname,apikey,admin,local,email"
}

func (o *user) InsertFields() string {
	return "usr,firstname,lastname,apikey,admin,local,email"
}

func (o *user) KeyField() string {
	return "usr"
}

func (o *user) KeyName() string {
	return "USR"
}

func (o *user) Names() []string {
	return []string{"First", "Last", "APIKey", "Level", "Local", "Email"}
}

func (o *user) ModifiedBy(user int64, t time.Time) {
}

//
// fullUser DBObject generator
//
func (o fullUser) NewObj() interface{} {
	return new(fullUser)
}

//
// fullUser DBObject interface functions
//
func (o *fullUser) InsertValues() []interface{} {
	return []interface{}{o.Last, o.APIKey, o.Password, o.Salt, o.Level, o.Local, o.Email, o.First}
}

func (o *fullUser) UpdateValues() []interface{} {
	return []interface{}{o.Last, o.APIKey, o.Password, o.Salt, o.Level, o.Local, o.Email, o.First, o.USR}
}

func (o *fullUser) MemberPointers() []interface{} {
	return []interface{}{&o.USR, &o.Last, &o.APIKey, &o.Password, &o.Salt, &o.Level, &o.Local, &o.Email, &o.First}
}

func (o *fullUser) Key() int64 {
	return o.USR
}

func (o *fullUser) SetID(id int64) {
	o.USR = id
}

func (o *fullUser) TableName() string {
	return "users"
}

func (o *fullUser) SelectFields() string {
	return "usr,lastname,apikey,pw_hash,pw_salt,admin,local,email,firstname"
}

func (o *fullUser) InsertFields() string {
	return "usr,lastname,apikey,pw_hash,pw_salt,admin,local,email,firstname"
}

func (o *fullUser) KeyField() string {
	return "usr"
}

func (o *fullUser) KeyName() string {
	return "USR"
}

func (o *fullUser) Names() []string {
	return []string{"Last", "APIKey", "Password", "Salt", "Level", "Local", "Email", "First"}
}

func (o *fullUser) ModifiedBy(user int64, t time.Time) {
}

//
// session DBObject generator
//
func (o session) NewObj() interface{} {
	return new(session)
}

//
// session DBObject interface functions
//
func (o *session) InsertValues() []interface{} {
	return []interface{}{o.TS, o.Event, o.Remote, o.USR}
}

func (o *session) UpdateValues() []interface{} {
	return []interface{}{o.TS, o.Event, o.Remote, o.USR, o.SSI}
}

func (o *session) MemberPointers() []interface{} {
	return []interface{}{&o.SSI, &o.TS, &o.Event, &o.Remote, &o.USR}
}

func (o *session) Key() int64 {
	return o.SSI
}

func (o *session) SetID(id int64) {
	o.SSI = id
}

func (o *session) TableName() string {
	return "sessions"
}

func (o *session) SelectFields() string {
	return "ssi,ts,event,remote_addr,usr"
}

func (o *session) InsertFields() string {
	return "ssi,ts,event,remote_addr,usr"
}

func (o *session) KeyField() string {
	return "ssi"
}

func (o *session) KeyName() string {
	return "SSI"
}

func (o *session) Names() []string {
	return []string{"TS", "Event", "Remote", "USR"}
}

func (o *session) ModifiedBy(user int64, t time.Time) {
}

//
// sessionView DBObject generator
//
func (o sessionView) NewObj() interface{} {
	return new(sessionView)
}

//
// sessionView DBObject interface functions
//
func (o *sessionView) InsertValues() []interface{} {
	return []interface{}{o.Event, o.Remote, o.USR, o.TS, o.Login}
}

func (o *sessionView) UpdateValues() []interface{} {
	return []interface{}{o.Event, o.Remote, o.USR, o.TS, o.Login, o.SSI}
}

func (o *sessionView) MemberPointers() []interface{} {
	return []interface{}{&o.SSI, &o.Event, &o.Remote, &o.USR, &o.TS, &o.Login}
}

func (o *sessionView) Key() int64 {
	return o.SSI
}

func (o *sessionView) SetID(id int64) {
	o.SSI = id
}

func (o *sessionView) TableName() string {
	return "sessions_view"
}

func (o *sessionView) SelectFields() string {
	return "ssi,event,remote_addr,usr,ts,login"
}

func (o *sessionView) InsertFields() string {
	return "ssi,event,remote_addr,usr,ts,login"
}

func (o *sessionView) KeyField() string {
	return "ssi"
}

func (o *sessionView) KeyName() string {
	return "SSI"
}

func (o *sessionView) Names() []string {
	return []string{"Event", "Remote", "USR", "TS", "Login"}
}

func (o *sessionView) ModifiedBy(user int64, t time.Time) {
}

//
// vendor DBObject generator
//
func (o vendor) NewObj() interface{} {
	return new(vendor)
}

//
// vendor DBObject interface functions
//
func (o *vendor) InsertValues() []interface{} {
	return []interface{}{o.TS, o.WWW, o.Phone, o.Address, o.City, o.Country, o.Note, o.Name, o.State, o.Postal, o.USR}
}

func (o *vendor) UpdateValues() []interface{} {
	return []interface{}{o.TS, o.WWW, o.Phone, o.Address, o.City, o.Country, o.Note, o.Name, o.State, o.Postal, o.USR, o.VID}
}

func (o *vendor) MemberPointers() []interface{} {
	return []interface{}{&o.VID, &o.TS, &o.WWW, &o.Phone, &o.Address, &o.City, &o.Country, &o.Note, &o.Name, &o.State, &o.Postal, &o.USR}
}

func (o *vendor) Key() int64 {
	return o.VID
}

func (o *vendor) SetID(id int64) {
	o.VID = id
}

func (o *vendor) TableName() string {
	return "vendors"
}

func (o *vendor) SelectFields() string {
	return "vid,ts,www,phone,address,city,country,note,name,state,postal,usr"
}

func (o *vendor) InsertFields() string {
	return "vid,ts,www,phone,address,city,country,note,name,state,postal,usr"
}

func (o *vendor) KeyField() string {
	return "vid"
}

func (o *vendor) KeyName() string {
	return "VID"
}

func (o *vendor) Names() []string {
	return []string{"TS", "WWW", "Phone", "Address", "City", "Country", "Note", "Name", "State", "Postal", "USR"}
}

func (o *vendor) ModifiedBy(user int64, t time.Time) {
	o.USR = &user
	o.TS = t
}

//
// ipType DBObject generator
//
func (o ipType) NewObj() interface{} {
	return new(ipType)
}

//
// ipType DBObject interface functions
//
func (o *ipType) InsertValues() []interface{} {
	return []interface{}{o.Name, o.Mgmt, o.Multi}
}

func (o *ipType) UpdateValues() []interface{} {
	return []interface{}{o.Name, o.Mgmt, o.Multi, o.IPT}
}

func (o *ipType) MemberPointers() []interface{} {
	return []interface{}{&o.IPT, &o.Name, &o.Mgmt, &o.Multi}
}

func (o *ipType) Key() int64 {
	return o.IPT
}

func (o *ipType) SetID(id int64) {
	o.IPT = id
}

func (o *ipType) TableName() string {
	return "ip_types"
}

func (o *ipType) SelectFields() string {
	return "ipt,name,mgmt,multi"
}

func (o *ipType) InsertFields() string {
	return "ipt,name,mgmt,multi"
}

func (o *ipType) KeyField() string {
	return "ipt"
}

func (o *ipType) KeyName() string {
	return "IPT"
}

func (o *ipType) Names() []string {
	return []string{"Name", "Mgmt", "Multi"}
}

func (o *ipType) ModifiedBy(user int64, t time.Time) {
}

//
// rma DBObject generator
//
func (o rma) NewObj() interface{} {
	return new(rma)
}

//
// rma DBObject interface functions
//
func (o *rma) InsertValues() []interface{} {
	return []interface{}{o.VID, o.NewPID, o.RecvTrack, o.STI, o.DID, o.Closed, o.Created, o.VendorRMA, o.ShipTrack, o.USR, o.Receiving, o.Received, o.DCTicket, o.Note, o.Shipped, o.OldPID, o.Jira}
}

func (o *rma) UpdateValues() []interface{} {
	return []interface{}{o.VID, o.NewPID, o.RecvTrack, o.STI, o.DID, o.Closed, o.Created, o.VendorRMA, o.ShipTrack, o.USR, o.Receiving, o.Received, o.DCTicket, o.Note, o.Shipped, o.OldPID, o.Jira, o.RMD}
}

func (o *rma) MemberPointers() []interface{} {
	return []interface{}{&o.RMD, &o.VID, &o.NewPID, &o.RecvTrack, &o.STI, &o.DID, &o.Closed, &o.Created, &o.VendorRMA, &o.ShipTrack, &o.USR, &o.Receiving, &o.Received, &o.DCTicket, &o.Note, &o.Shipped, &o.OldPID, &o.Jira}
}

func (o *rma) Key() int64 {
	return o.RMD
}

func (o *rma) SetID(id int64) {
	o.RMD = id
}

func (o *rma) TableName() string {
	return "rmas"
}

func (o *rma) SelectFields() string {
	return "rmd,vid,new_pid,recv_tracking,sti,did,date_closed,date_created,vendor_rma,ship_tracking,usr,dc_receiving,date_received,dc_ticket,note,date_shipped,old_pid,jira"
}

func (o *rma) InsertFields() string {
	return "rmd,vid,new_pid,recv_tracking,sti,did,date_closed,date_created,vendor_rma,ship_tracking,usr,dc_receiving,date_received,dc_ticket,note,date_shipped,old_pid,jira"
}

func (o *rma) KeyField() string {
	return "rmd"
}

func (o *rma) KeyName() string {
	return "RMD"
}

func (o *rma) Names() []string {
	return []string{"VID", "NewPID", "RecvTrack", "STI", "DID", "Closed", "Created", "VendorRMA", "ShipTrack", "USR", "Receiving", "Received", "DCTicket", "Note", "Shipped", "OldPID", "Jira"}
}

func (o *rma) ModifiedBy(user int64, t time.Time) {
}

//
// rmaView DBObject generator
//
func (o rmaView) NewObj() interface{} {
	return new(rmaView)
}

//
// rmaView DBObject interface functions
//
func (o *rmaView) InsertValues() []interface{} {
	return []interface{}{o.VendorRMA, o.DCTicket, o.STI, o.NewPID, o.Hostname, o.Description, o.PartSN, o.PartNumber, o.USR, o.Shipped, o.Received, o.OldPID, o.Site, o.DeviceSN, o.RecvTrack, o.Receiving, o.Note, o.Closed, o.DID, o.VID, o.Vendor, o.Jira, o.ShipTrack, o.Created}
}

func (o *rmaView) UpdateValues() []interface{} {
	return []interface{}{o.VendorRMA, o.DCTicket, o.STI, o.NewPID, o.Hostname, o.Description, o.PartSN, o.PartNumber, o.USR, o.Shipped, o.Received, o.OldPID, o.Site, o.DeviceSN, o.RecvTrack, o.Receiving, o.Note, o.Closed, o.DID, o.VID, o.Vendor, o.Jira, o.ShipTrack, o.Created, o.RMD}
}

func (o *rmaView) MemberPointers() []interface{} {
	return []interface{}{&o.RMD, &o.VendorRMA, &o.DCTicket, &o.STI, &o.NewPID, &o.Hostname, &o.Description, &o.PartSN, &o.PartNumber, &o.USR, &o.Shipped, &o.Received, &o.OldPID, &o.Site, &o.DeviceSN, &o.RecvTrack, &o.Receiving, &o.Note, &o.Closed, &o.DID, &o.VID, &o.Vendor, &o.Jira, &o.ShipTrack, &o.Created}
}

func (o *rmaView) Key() int64 {
	return o.RMD
}

func (o *rmaView) SetID(id int64) {
	o.RMD = id
}

func (o *rmaView) TableName() string {
	return "rmas_view"
}

func (o *rmaView) SelectFields() string {
	return "rmd,vendor_rma,dc_ticket,sti,new_pid,hostname,description,part_sn,part_no,usr,date_shipped,date_received,old_pid,site,device_sn,recv_tracking,dc_receiving,note,date_closed,did,vid,vendor,jira,ship_tracking,date_created"
}

func (o *rmaView) InsertFields() string {
	return "rmd,vendor_rma,dc_ticket,sti,new_pid,hostname,description,part_sn,part_no,usr,date_shipped,date_received,old_pid,site,device_sn,recv_tracking,dc_receiving,note,date_closed,did,vid,vendor,jira,ship_tracking,date_created"
}

func (o *rmaView) KeyField() string {
	return "rmd"
}

func (o *rmaView) KeyName() string {
	return "RMD"
}

func (o *rmaView) Names() []string {
	return []string{"VendorRMA", "DCTicket", "STI", "NewPID", "Hostname", "Description", "PartSN", "PartNumber", "USR", "Shipped", "Received", "OldPID", "Site", "DeviceSN", "RecvTrack", "Receiving", "Note", "Closed", "DID", "VID", "Vendor", "Jira", "ShipTrack", "Created"}
}

func (o *rmaView) ModifiedBy(user int64, t time.Time) {
}

//
// manufacturer DBObject generator
//
func (o manufacturer) NewObj() interface{} {
	return new(manufacturer)
}

//
// manufacturer DBObject interface functions
//
func (o *manufacturer) InsertValues() []interface{} {
	return []interface{}{o.Note, o.AKA, o.URL, o.USR, o.TS, o.Name}
}

func (o *manufacturer) UpdateValues() []interface{} {
	return []interface{}{o.Note, o.AKA, o.URL, o.USR, o.TS, o.Name, o.MID}
}

func (o *manufacturer) MemberPointers() []interface{} {
	return []interface{}{&o.MID, &o.Note, &o.AKA, &o.URL, &o.USR, &o.TS, &o.Name}
}

func (o *manufacturer) Key() int64 {
	return o.MID
}

func (o *manufacturer) SetID(id int64) {
	o.MID = id
}

func (o *manufacturer) TableName() string {
	return "mfgrs"
}

func (o *manufacturer) SelectFields() string {
	return "mid,note,aka,url,usr,ts,name"
}

func (o *manufacturer) InsertFields() string {
	return "mid,note,aka,url,usr,ts,name"
}

func (o *manufacturer) KeyField() string {
	return "mid"
}

func (o *manufacturer) KeyName() string {
	return "MID"
}

func (o *manufacturer) Names() []string {
	return []string{"Note", "AKA", "URL", "USR", "TS", "Name"}
}

func (o *manufacturer) ModifiedBy(user int64, t time.Time) {
	o.USR = &user
	o.TS = t
}

//
// partType DBObject generator
//
func (o partType) NewObj() interface{} {
	return new(partType)
}

//
// partType DBObject interface functions
//
func (o *partType) InsertValues() []interface{} {
	return []interface{}{o.TS, o.Name, o.USR}
}

func (o *partType) UpdateValues() []interface{} {
	return []interface{}{o.TS, o.Name, o.USR, o.PTI}
}

func (o *partType) MemberPointers() []interface{} {
	return []interface{}{&o.PTI, &o.TS, &o.Name, &o.USR}
}

func (o *partType) Key() int64 {
	return o.PTI
}

func (o *partType) SetID(id int64) {
	o.PTI = id
}

func (o *partType) TableName() string {
	return "part_types"
}

func (o *partType) SelectFields() string {
	return "pti,ts,name,usr"
}

func (o *partType) InsertFields() string {
	return "pti,ts,name,usr"
}

func (o *partType) KeyField() string {
	return "pti"
}

func (o *partType) KeyName() string {
	return "PTI"
}

func (o *partType) Names() []string {
	return []string{"TS", "Name", "USR"}
}

func (o *partType) ModifiedBy(user int64, t time.Time) {
	o.USR = &user
	o.TS = t
}

//
// sku DBObject generator
//
func (o sku) NewObj() interface{} {
	return new(sku)
}

//
// sku DBObject interface functions
//
func (o *sku) InsertValues() []interface{} {
	return []interface{}{o.Description, o.SKU, o.USR, o.TS, o.MID, o.PTI, o.PartNumber}
}

func (o *sku) UpdateValues() []interface{} {
	return []interface{}{o.Description, o.SKU, o.USR, o.TS, o.MID, o.PTI, o.PartNumber, o.KID}
}

func (o *sku) MemberPointers() []interface{} {
	return []interface{}{&o.KID, &o.Description, &o.SKU, &o.USR, &o.TS, &o.MID, &o.PTI, &o.PartNumber}
}

func (o *sku) Key() int64 {
	return o.KID
}

func (o *sku) SetID(id int64) {
	o.KID = id
}

func (o *sku) TableName() string {
	return "skus"
}

func (o *sku) SelectFields() string {
	return "kid,description,sku,usr,ts,mid,pti,part_no"
}

func (o *sku) InsertFields() string {
	return "kid,description,sku,usr,ts,mid,pti,part_no"
}

func (o *sku) KeyField() string {
	return "kid"
}

func (o *sku) KeyName() string {
	return "KID"
}

func (o *sku) Names() []string {
	return []string{"Description", "SKU", "USR", "TS", "MID", "PTI", "PartNumber"}
}

func (o *sku) ModifiedBy(user int64, t time.Time) {
	o.USR = &user
	o.TS = t
}

//
// part DBObject generator
//
func (o part) NewObj() interface{} {
	return new(part)
}

//
// part DBObject interface functions
//
func (o *part) InsertValues() []interface{} {
	return []interface{}{o.Cents, o.KID, o.Serial, o.Unused, o.Bad, o.AssetTag, o.USR, o.TS, o.VID, o.DID, o.STI, o.Location}
}

func (o *part) UpdateValues() []interface{} {
	return []interface{}{o.Cents, o.KID, o.Serial, o.Unused, o.Bad, o.AssetTag, o.USR, o.TS, o.VID, o.DID, o.STI, o.Location, o.PID}
}

func (o *part) MemberPointers() []interface{} {
	return []interface{}{&o.PID, &o.Cents, &o.KID, &o.Serial, &o.Unused, &o.Bad, &o.AssetTag, &o.USR, &o.TS, &o.VID, &o.DID, &o.STI, &o.Location}
}

func (o *part) Key() int64 {
	return o.PID
}

func (o *part) SetID(id int64) {
	o.PID = id
}

func (o *part) TableName() string {
	return "parts"
}

func (o *part) SelectFields() string {
	return "pid,cents,kid,serial_no,unused,bad,asset_tag,usr,ts,vid,did,sti,location"
}

func (o *part) InsertFields() string {
	return "pid,cents,kid,serial_no,unused,bad,asset_tag,usr,ts,vid,did,sti,location"
}

func (o *part) KeyField() string {
	return "pid"
}

func (o *part) KeyName() string {
	return "PID"
}

func (o *part) Names() []string {
	return []string{"Cents", "KID", "Serial", "Unused", "Bad", "AssetTag", "USR", "TS", "VID", "DID", "STI", "Location"}
}

func (o *part) ModifiedBy(user int64, t time.Time) {
	o.USR = &user
	o.TS = t
}

//
// partView DBObject generator
//
func (o partView) NewObj() interface{} {
	return new(partView)
}

//
// partView DBObject interface functions
//
func (o *partView) InsertValues() []interface{} {
	return []interface{}{o.Hostname, o.Serial, o.Cents, o.Unused, o.DID, o.AssetTag, o.SKU, o.Bad, o.Site, o.DeviceSN, o.KID, o.VID, o.STI, o.RMD, o.Mfgr, o.Vendor, o.Price, o.Location, o.PartType, o.PartNumber, o.Description}
}

func (o *partView) UpdateValues() []interface{} {
	return []interface{}{o.Hostname, o.Serial, o.Cents, o.Unused, o.DID, o.AssetTag, o.SKU, o.Bad, o.Site, o.DeviceSN, o.KID, o.VID, o.STI, o.RMD, o.Mfgr, o.Vendor, o.Price, o.Location, o.PartType, o.PartNumber, o.Description, o.PID}
}

func (o *partView) MemberPointers() []interface{} {
	return []interface{}{&o.PID, &o.Hostname, &o.Serial, &o.Cents, &o.Unused, &o.DID, &o.AssetTag, &o.SKU, &o.Bad, &o.Site, &o.DeviceSN, &o.KID, &o.VID, &o.STI, &o.RMD, &o.Mfgr, &o.Vendor, &o.Price, &o.Location, &o.PartType, &o.PartNumber, &o.Description}
}

func (o *partView) Key() int64 {
	return o.PID
}

func (o *partView) SetID(id int64) {
	o.PID = id
}

func (o *partView) TableName() string {
	return "parts_view"
}

func (o *partView) SelectFields() string {
	return "pid,hostname,serial_no,cents,unused,did,asset_tag,sku,bad,site,device_sn,kid,vid,sti,rmd,mfgr,vendor,price,location,part_type,part_no,description"
}

func (o *partView) InsertFields() string {
	return "pid,hostname,serial_no,cents,unused,did,asset_tag,sku,bad,site,device_sn,kid,vid,sti,rmd,mfgr,vendor,price,location,part_type,part_no,description"
}

func (o *partView) KeyField() string {
	return "pid"
}

func (o *partView) KeyName() string {
	return "PID"
}

func (o *partView) Names() []string {
	return []string{"Hostname", "Serial", "Cents", "Unused", "DID", "AssetTag", "SKU", "Bad", "Site", "DeviceSN", "KID", "VID", "STI", "RMD", "Mfgr", "Vendor", "Price", "Location", "PartType", "PartNumber", "Description"}
}

func (o *partView) ModifiedBy(user int64, t time.Time) {
}

//
// site DBObject generator
//
func (o site) NewObj() interface{} {
	return new(site)
}

//
// site DBObject interface functions
//
func (o *site) InsertValues() []interface{} {
	return []interface{}{o.Name, o.Country, o.Note, o.TS, o.Web, o.USR, o.Address, o.City, o.State, o.Postal, o.Phone}
}

func (o *site) UpdateValues() []interface{} {
	return []interface{}{o.Name, o.Country, o.Note, o.TS, o.Web, o.USR, o.Address, o.City, o.State, o.Postal, o.Phone, o.STI}
}

func (o *site) MemberPointers() []interface{} {
	return []interface{}{&o.STI, &o.Name, &o.Country, &o.Note, &o.TS, &o.Web, &o.USR, &o.Address, &o.City, &o.State, &o.Postal, &o.Phone}
}

func (o *site) Key() int64 {
	return o.STI
}

func (o *site) SetID(id int64) {
	o.STI = id
}

func (o *site) TableName() string {
	return "sites"
}

func (o *site) SelectFields() string {
	return "sti,name,country,note,ts,web,usr,address,city,state,postal,phone"
}

func (o *site) InsertFields() string {
	return "sti,name,country,note,ts,web,usr,address,city,state,postal,phone"
}

func (o *site) KeyField() string {
	return "sti"
}

func (o *site) KeyName() string {
	return "STI"
}

func (o *site) Names() []string {
	return []string{"Name", "Country", "Note", "TS", "Web", "USR", "Address", "City", "State", "Postal", "Phone"}
}

func (o *site) ModifiedBy(user int64, t time.Time) {
	o.USR = &user
	o.TS = t
}

//
// tag DBObject generator
//
func (o tag) NewObj() interface{} {
	return new(tag)
}

//
// tag DBObject interface functions
//
func (o *tag) InsertValues() []interface{} {
	return []interface{}{o.Name}
}

func (o *tag) UpdateValues() []interface{} {
	return []interface{}{o.Name, o.TID}
}

func (o *tag) MemberPointers() []interface{} {
	return []interface{}{&o.TID, &o.Name}
}

func (o *tag) Key() int64 {
	return o.TID
}

func (o *tag) SetID(id int64) {
	o.TID = id
}

func (o *tag) TableName() string {
	return "tags"
}

func (o *tag) SelectFields() string {
	return "tid,tag"
}

func (o *tag) InsertFields() string {
	return "tid,tag"
}

func (o *tag) KeyField() string {
	return "tid"
}

func (o *tag) KeyName() string {
	return "TID"
}

func (o *tag) Names() []string {
	return []string{"Name"}
}

func (o *tag) ModifiedBy(user int64, t time.Time) {
}

//
// rack DBObject generator
//
func (o rack) NewObj() interface{} {
	return new(rack)
}

//
// rack DBObject interface functions
//
func (o *rack) InsertValues() []interface{} {
	return []interface{}{o.Label, o.XPos, o.TS, o.STI, o.RUs, o.VendorID, o.YPos, o.Note, o.USR}
}

func (o *rack) UpdateValues() []interface{} {
	return []interface{}{o.Label, o.XPos, o.TS, o.STI, o.RUs, o.VendorID, o.YPos, o.Note, o.USR, o.RID}
}

func (o *rack) MemberPointers() []interface{} {
	return []interface{}{&o.RID, &o.Label, &o.XPos, &o.TS, &o.STI, &o.RUs, &o.VendorID, &o.YPos, &o.Note, &o.USR}
}

func (o *rack) Key() int64 {
	return o.RID
}

func (o *rack) SetID(id int64) {
	o.RID = id
}

func (o *rack) TableName() string {
	return "racks"
}

func (o *rack) SelectFields() string {
	return "rid,rack,x_pos,ts,sti,rackunits,vendor_id,y_pos,note,usr"
}

func (o *rack) InsertFields() string {
	return "rid,rack,x_pos,ts,sti,rackunits,vendor_id,y_pos,note,usr"
}

func (o *rack) KeyField() string {
	return "rid"
}

func (o *rack) KeyName() string {
	return "RID"
}

func (o *rack) Names() []string {
	return []string{"Label", "XPos", "TS", "STI", "RUs", "VendorID", "YPos", "Note", "USR"}
}

func (o *rack) ModifiedBy(user int64, t time.Time) {
}

//
// rackView DBObject generator
//
func (o rackView) NewObj() interface{} {
	return new(rackView)
}

//
// rackView DBObject interface functions
//
func (o *rackView) InsertValues() []interface{} {
	return []interface{}{o.Label, o.XPos, o.YPos, o.STI, o.RUs, o.Note, o.USR, o.TS, o.Site, o.VendorID}
}

func (o *rackView) UpdateValues() []interface{} {
	return []interface{}{o.Label, o.XPos, o.YPos, o.STI, o.RUs, o.Note, o.USR, o.TS, o.Site, o.VendorID, o.RID}
}

func (o *rackView) MemberPointers() []interface{} {
	return []interface{}{&o.RID, &o.Label, &o.XPos, &o.YPos, &o.STI, &o.RUs, &o.Note, &o.USR, &o.TS, &o.Site, &o.VendorID}
}

func (o *rackView) Key() int64 {
	return o.RID
}

func (o *rackView) SetID(id int64) {
	o.RID = id
}

func (o *rackView) TableName() string {
	return "racks_view"
}

func (o *rackView) SelectFields() string {
	return "rid,rack,x_pos,y_pos,sti,rackunits,note,usr,ts,site,vendor_id"
}

func (o *rackView) InsertFields() string {
	return "rid,rack,x_pos,y_pos,sti,rackunits,note,usr,ts,site,vendor_id"
}

func (o *rackView) KeyField() string {
	return "rid"
}

func (o *rackView) KeyName() string {
	return "RID"
}

func (o *rackView) Names() []string {
	return []string{"Label", "XPos", "YPos", "STI", "RUs", "Note", "USR", "TS", "Site", "VendorID"}
}

func (o *rackView) ModifiedBy(user int64, t time.Time) {
}

//
// vm DBObject generator
//
func (o vm) NewObj() interface{} {
	return new(vm)
}

//
// vm DBObject interface functions
//
func (o *vm) InsertValues() []interface{} {
	return []interface{}{o.TS, o.DID, o.Hostname, o.Profile, o.Note, o.USR}
}

func (o *vm) UpdateValues() []interface{} {
	return []interface{}{o.TS, o.DID, o.Hostname, o.Profile, o.Note, o.USR, o.VMI}
}

func (o *vm) MemberPointers() []interface{} {
	return []interface{}{&o.VMI, &o.TS, &o.DID, &o.Hostname, &o.Profile, &o.Note, &o.USR}
}

func (o *vm) Key() int64 {
	return o.VMI
}

func (o *vm) SetID(id int64) {
	o.VMI = id
}

func (o *vm) TableName() string {
	return "vms"
}

func (o *vm) SelectFields() string {
	return "vmi,ts,did,hostname,profile,note,usr"
}

func (o *vm) InsertFields() string {
	return "vmi,ts,did,hostname,profile,note,usr"
}

func (o *vm) KeyField() string {
	return "vmi"
}

func (o *vm) KeyName() string {
	return "VMI"
}

func (o *vm) Names() []string {
	return []string{"TS", "DID", "Hostname", "Profile", "Note", "USR"}
}

func (o *vm) ModifiedBy(user int64, t time.Time) {
	o.USR = &user
	o.TS = t
}

//
// vmView DBObject generator
//
func (o vmView) NewObj() interface{} {
	return new(vmView)
}

//
// vmView DBObject interface functions
//
func (o *vmView) InsertValues() []interface{} {
	return []interface{}{o.TS, o.DID, o.RID, o.STI, o.Rack, o.Version, o.USR, o.Site, o.Server, o.Hostname, o.Profile, o.Note}
}

func (o *vmView) UpdateValues() []interface{} {
	return []interface{}{o.TS, o.DID, o.RID, o.STI, o.Rack, o.Version, o.USR, o.Site, o.Server, o.Hostname, o.Profile, o.Note, o.VMI}
}

func (o *vmView) MemberPointers() []interface{} {
	return []interface{}{&o.VMI, &o.TS, &o.DID, &o.RID, &o.STI, &o.Rack, &o.Version, &o.USR, &o.Site, &o.Server, &o.Hostname, &o.Profile, &o.Note}
}

func (o *vmView) Key() int64 {
	return o.VMI
}

func (o *vmView) SetID(id int64) {
	o.VMI = id
}

func (o *vmView) TableName() string {
	return "vms_view"
}

func (o *vmView) SelectFields() string {
	return "vmi,ts,did,rid,sti,rack,version,usr,site,server,hostname,profile,note"
}

func (o *vmView) InsertFields() string {
	return "vmi,ts,did,rid,sti,rack,version,usr,site,server,hostname,profile,note"
}

func (o *vmView) KeyField() string {
	return "vmi"
}

func (o *vmView) KeyName() string {
	return "VMI"
}

func (o *vmView) Names() []string {
	return []string{"TS", "DID", "RID", "STI", "Rack", "Version", "USR", "Site", "Server", "Hostname", "Profile", "Note"}
}

func (o *vmView) ModifiedBy(user int64, t time.Time) {
	o.USR = &user
	o.TS = t
}

//
// vmIPs DBObject generator
//
func (o vmIPs) NewObj() interface{} {
	return new(vmIPs)
}

//
// vmIPs DBObject interface functions
//
func (o *vmIPs) InsertValues() []interface{} {
	return []interface{}{o.RID, o.Site, o.Hostname, o.Profile, o.IPs, o.Note, o.USR, o.TS, o.DID, o.STI, o.Rack, o.RU, o.Server}
}

func (o *vmIPs) UpdateValues() []interface{} {
	return []interface{}{o.RID, o.Site, o.Hostname, o.Profile, o.IPs, o.Note, o.USR, o.TS, o.DID, o.STI, o.Rack, o.RU, o.Server, o.VMI}
}

func (o *vmIPs) MemberPointers() []interface{} {
	return []interface{}{&o.VMI, &o.RID, &o.Site, &o.Hostname, &o.Profile, &o.IPs, &o.Note, &o.USR, &o.TS, &o.DID, &o.STI, &o.Rack, &o.RU, &o.Server}
}

func (o *vmIPs) Key() int64 {
	return o.VMI
}

func (o *vmIPs) SetID(id int64) {
	o.VMI = id
}

func (o *vmIPs) TableName() string {
	return "vms_list"
}

func (o *vmIPs) SelectFields() string {
	return "vmi,rid,site,hostname,profile,ips,note,usr,ts,did,sti,rack,ru,server"
}

func (o *vmIPs) InsertFields() string {
	return "vmi,rid,site,hostname,profile,ips,note,usr,ts,did,sti,rack,ru,server"
}

func (o *vmIPs) KeyField() string {
	return "vmi"
}

func (o *vmIPs) KeyName() string {
	return "VMI"
}

func (o *vmIPs) Names() []string {
	return []string{"RID", "Site", "Hostname", "Profile", "IPs", "Note", "USR", "TS", "DID", "STI", "Rack", "RU", "Server"}
}

func (o *vmIPs) ModifiedBy(user int64, t time.Time) {
}

//
// vmHistory DBObject generator
//
func (o vmHistory) NewObj() interface{} {
	return new(vmHistory)
}

//
// vmHistory DBObject interface functions
//
func (o *vmHistory) InsertValues() []interface{} {
	return []interface{}{o.Note, o.Login, o.Version, o.USR, o.RID, o.Rack, o.Hostname, o.Server, o.Profile, o.TS, o.DID, o.STI, o.Site}
}

func (o *vmHistory) UpdateValues() []interface{} {
	return []interface{}{o.Note, o.Login, o.Version, o.USR, o.RID, o.Rack, o.Hostname, o.Server, o.Profile, o.TS, o.DID, o.STI, o.Site, o.VMI}
}

func (o *vmHistory) MemberPointers() []interface{} {
	return []interface{}{&o.VMI, &o.Note, &o.Login, &o.Version, &o.USR, &o.RID, &o.Rack, &o.Hostname, &o.Server, &o.Profile, &o.TS, &o.DID, &o.STI, &o.Site}
}

func (o *vmHistory) Key() int64 {
	return o.VMI
}

func (o *vmHistory) SetID(id int64) {
	o.VMI = id
}

func (o *vmHistory) TableName() string {
	return "vms_history"
}

func (o *vmHistory) SelectFields() string {
	return "vmi,note,login,version,usr,rid,rack,hostname,server,profile,ts,did,sti,site"
}

func (o *vmHistory) InsertFields() string {
	return "vmi,note,login,version,usr,rid,rack,hostname,server,profile,ts,did,sti,site"
}

func (o *vmHistory) KeyField() string {
	return "vmi"
}

func (o *vmHistory) KeyName() string {
	return "VMI"
}

func (o *vmHistory) Names() []string {
	return []string{"Note", "Login", "Version", "USR", "RID", "Rack", "Hostname", "Server", "Profile", "TS", "DID", "STI", "Site"}
}

func (o *vmHistory) ModifiedBy(user int64, t time.Time) {
}

//
// inventory DBObject generator
//
func (o inventory) NewObj() interface{} {
	return new(inventory)
}

//
// inventory DBObject interface functions
//
func (o *inventory) InsertValues() []interface{} {
	return []interface{}{o.PartNumber, o.PartType, o.Description, o.Cents, o.Mfgr, o.PTI, o.Qty, o.Site, o.Price, o.KID}
}

func (o *inventory) UpdateValues() []interface{} {
	return []interface{}{o.PartNumber, o.PartType, o.Description, o.Cents, o.Mfgr, o.PTI, o.Qty, o.Site, o.Price, o.KID, o.STI}
}

func (o *inventory) MemberPointers() []interface{} {
	return []interface{}{&o.STI, &o.PartNumber, &o.PartType, &o.Description, &o.Cents, &o.Mfgr, &o.PTI, &o.Qty, &o.Site, &o.Price, &o.KID}
}

func (o *inventory) Key() int64 {
	return o.STI
}

func (o *inventory) SetID(id int64) {
	o.STI = id
}

func (o *inventory) TableName() string {
	return "inventory"
}

func (o *inventory) SelectFields() string {
	return "sti,part_no,part_type,description,cents,mfgr,pti,qty,site,price,kid"
}

func (o *inventory) InsertFields() string {
	return "sti,part_no,part_type,description,cents,mfgr,pti,qty,site,price,kid"
}

func (o *inventory) KeyField() string {
	return "sti"
}

func (o *inventory) KeyName() string {
	return "STI"
}

func (o *inventory) Names() []string {
	return []string{"PartNumber", "PartType", "Description", "Cents", "Mfgr", "PTI", "Qty", "Site", "Price", "KID"}
}

func (o *inventory) ModifiedBy(user int64, t time.Time) {
}

//
// contract DBObject generator
//
func (o contract) NewObj() interface{} {
	return new(contract)
}

//
// contract DBObject interface functions
//
func (o *contract) InsertValues() []interface{} {
	return []interface{}{o.Policy, o.Phone, o.VID}
}

func (o *contract) UpdateValues() []interface{} {
	return []interface{}{o.Policy, o.Phone, o.VID, o.CID}
}

func (o *contract) MemberPointers() []interface{} {
	return []interface{}{&o.CID, &o.Policy, &o.Phone, &o.VID}
}

func (o *contract) Key() int64 {
	return o.CID
}

func (o *contract) SetID(id int64) {
	o.CID = id
}

func (o *contract) TableName() string {
	return "contracts"
}

func (o *contract) SelectFields() string {
	return "cid,policy,phone,vid"
}

func (o *contract) InsertFields() string {
	return "cid,policy,phone,vid"
}

func (o *contract) KeyField() string {
	return "cid"
}

func (o *contract) KeyName() string {
	return "CID"
}

func (o *contract) Names() []string {
	return []string{"Policy", "Phone", "VID"}
}

func (o *contract) ModifiedBy(user int64, t time.Time) {
}

//
// deviceType DBObject generator
//
func (o deviceType) NewObj() interface{} {
	return new(deviceType)
}

//
// deviceType DBObject interface functions
//
func (o *deviceType) InsertValues() []interface{} {
	return []interface{}{o.Name}
}

func (o *deviceType) UpdateValues() []interface{} {
	return []interface{}{o.Name, o.DTI}
}

func (o *deviceType) MemberPointers() []interface{} {
	return []interface{}{&o.DTI, &o.Name}
}

func (o *deviceType) Key() int64 {
	return o.DTI
}

func (o *deviceType) SetID(id int64) {
	o.DTI = id
}

func (o *deviceType) TableName() string {
	return "device_types"
}

func (o *deviceType) SelectFields() string {
	return "dti,name"
}

func (o *deviceType) InsertFields() string {
	return "dti,name"
}

func (o *deviceType) KeyField() string {
	return "dti"
}

func (o *deviceType) KeyName() string {
	return "DTI"
}

func (o *deviceType) Names() []string {
	return []string{"Name"}
}

func (o *deviceType) ModifiedBy(user int64, t time.Time) {
}

//
// device DBObject generator
//
func (o device) NewObj() interface{} {
	return new(device)
}

//
// device DBObject interface functions
//
func (o *device) InsertValues() []interface{} {
	return []interface{}{o.RID, o.MID, o.TID, o.Profile, o.DTI, o.Height, o.Model, o.AssetTag, o.Assigned, o.Note, o.RU, o.Hostname, o.Alias, o.SerialNo, o.USR, o.TS}
}

func (o *device) UpdateValues() []interface{} {
	return []interface{}{o.RID, o.MID, o.TID, o.Profile, o.DTI, o.Height, o.Model, o.AssetTag, o.Assigned, o.Note, o.RU, o.Hostname, o.Alias, o.SerialNo, o.USR, o.TS, o.DID}
}

func (o *device) MemberPointers() []interface{} {
	return []interface{}{&o.DID, &o.RID, &o.MID, &o.TID, &o.Profile, &o.DTI, &o.Height, &o.Model, &o.AssetTag, &o.Assigned, &o.Note, &o.RU, &o.Hostname, &o.Alias, &o.SerialNo, &o.USR, &o.TS}
}

func (o *device) Key() int64 {
	return o.DID
}

func (o *device) SetID(id int64) {
	o.DID = id
}

func (o *device) TableName() string {
	return "devices"
}

func (o *device) SelectFields() string {
	return "did,rid,mid,tid,profile,dti,height,model,asset_tag,assigned,note,ru,hostname,alias,sn,usr,ts"
}

func (o *device) InsertFields() string {
	return "did,rid,mid,tid,profile,dti,height,model,asset_tag,assigned,note,ru,hostname,alias,sn,usr,ts"
}

func (o *device) KeyField() string {
	return "did"
}

func (o *device) KeyName() string {
	return "DID"
}

func (o *device) Names() []string {
	return []string{"RID", "MID", "TID", "Profile", "DTI", "Height", "Model", "AssetTag", "Assigned", "Note", "RU", "Hostname", "Alias", "SerialNo", "USR", "TS"}
}

func (o *device) ModifiedBy(user int64, t time.Time) {
	o.USR = &user
	o.TS = t
}

//
// deviceView DBObject generator
//
func (o deviceView) NewObj() interface{} {
	return new(deviceView)
}

//
// deviceView DBObject interface functions
//
func (o *deviceView) InsertValues() []interface{} {
	return []interface{}{o.Assigned, o.Tag, o.Site, o.Height, o.Alias, o.Make, o.Model, o.AssetTag, o.MID, o.SerialNo, o.Note, o.Type, o.Version, o.USR, o.DTI, o.Rack, o.RU, o.Hostname, o.Profile, o.STI, o.RID, o.TID, o.TS}
}

func (o *deviceView) UpdateValues() []interface{} {
	return []interface{}{o.Assigned, o.Tag, o.Site, o.Height, o.Alias, o.Make, o.Model, o.AssetTag, o.MID, o.SerialNo, o.Note, o.Type, o.Version, o.USR, o.DTI, o.Rack, o.RU, o.Hostname, o.Profile, o.STI, o.RID, o.TID, o.TS, o.DID}
}

func (o *deviceView) MemberPointers() []interface{} {
	return []interface{}{&o.DID, &o.Assigned, &o.Tag, &o.Site, &o.Height, &o.Alias, &o.Make, &o.Model, &o.AssetTag, &o.MID, &o.SerialNo, &o.Note, &o.Type, &o.Version, &o.USR, &o.DTI, &o.Rack, &o.RU, &o.Hostname, &o.Profile, &o.STI, &o.RID, &o.TID, &o.TS}
}

func (o *deviceView) Key() int64 {
	return o.DID
}

func (o *deviceView) SetID(id int64) {
	o.DID = id
}

func (o *deviceView) TableName() string {
	return "devices_view"
}

func (o *deviceView) SelectFields() string {
	return "did,assigned,tag,site,height,alias,make,model,asset_tag,mid,sn,note,devtype,version,usr,dti,rack,ru,hostname,profile,sti,rid,tid,ts"
}

func (o *deviceView) InsertFields() string {
	return "did,assigned,tag,site,height,alias,make,model,asset_tag,mid,sn,note,devtype,version,usr,dti,rack,ru,hostname,profile,sti,rid,tid,ts"
}

func (o *deviceView) KeyField() string {
	return "did"
}

func (o *deviceView) KeyName() string {
	return "DID"
}

func (o *deviceView) Names() []string {
	return []string{"Assigned", "Tag", "Site", "Height", "Alias", "Make", "Model", "AssetTag", "MID", "SerialNo", "Note", "Type", "Version", "USR", "DTI", "Rack", "RU", "Hostname", "Profile", "STI", "RID", "TID", "TS"}
}

func (o *deviceView) ModifiedBy(user int64, t time.Time) {
	o.USR = &user
	o.TS = t
}

//
// deviceHistory DBObject generator
//
func (o deviceHistory) NewObj() interface{} {
	return new(deviceHistory)
}

//
// deviceHistory DBObject interface functions
//
func (o *deviceHistory) InsertValues() []interface{} {
	return []interface{}{o.Type, o.Site, o.Login, o.Version, o.Rack, o.AssetTag, o.Alias, o.SerialNo, o.TS, o.RU, o.Hostname, o.Note, o.RID, o.DTI, o.TID, o.Height, o.Profile, o.Assigned, o.STI, o.KID, o.Tag, o.USR}
}

func (o *deviceHistory) UpdateValues() []interface{} {
	return []interface{}{o.Type, o.Site, o.Login, o.Version, o.Rack, o.AssetTag, o.Alias, o.SerialNo, o.TS, o.RU, o.Hostname, o.Note, o.RID, o.DTI, o.TID, o.Height, o.Profile, o.Assigned, o.STI, o.KID, o.Tag, o.USR, o.DID}
}

func (o *deviceHistory) MemberPointers() []interface{} {
	return []interface{}{&o.DID, &o.Type, &o.Site, &o.Login, &o.Version, &o.Rack, &o.AssetTag, &o.Alias, &o.SerialNo, &o.TS, &o.RU, &o.Hostname, &o.Note, &o.RID, &o.DTI, &o.TID, &o.Height, &o.Profile, &o.Assigned, &o.STI, &o.KID, &o.Tag, &o.USR}
}

func (o *deviceHistory) Key() int64 {
	return o.DID
}

func (o *deviceHistory) SetID(id int64) {
	o.DID = id
}

func (o *deviceHistory) TableName() string {
	return "devices_history"
}

func (o *deviceHistory) SelectFields() string {
	return "did,devtype,site,login,version,rack,asset_tag,alias,sn,ts,ru,hostname,note,rid,dti,tid,height,profile,assigned,sti,kid,tag,usr"
}

func (o *deviceHistory) InsertFields() string {
	return "did,devtype,site,login,version,rack,asset_tag,alias,sn,ts,ru,hostname,note,rid,dti,tid,height,profile,assigned,sti,kid,tag,usr"
}

func (o *deviceHistory) KeyField() string {
	return "did"
}

func (o *deviceHistory) KeyName() string {
	return "DID"
}

func (o *deviceHistory) Names() []string {
	return []string{"Type", "Site", "Login", "Version", "Rack", "AssetTag", "Alias", "SerialNo", "TS", "RU", "Hostname", "Note", "RID", "DTI", "TID", "Height", "Profile", "Assigned", "STI", "KID", "Tag", "USR"}
}

func (o *deviceHistory) ModifiedBy(user int64, t time.Time) {
}

//
// deviceIPs DBObject generator
//
func (o deviceIPs) NewObj() interface{} {
	return new(deviceIPs)
}

//
// deviceIPs DBObject interface functions
//
func (o *deviceIPs) InsertValues() []interface{} {
	return []interface{}{o.Tag, o.Note, o.USR, o.TS, o.TID, o.Hostname, o.SerialNo, o.AssetTag, o.Make, o.Model, o.DTI, o.Rack, o.RU, o.Profile, o.Site, o.RID, o.Height, o.Mgmt, o.Alias, o.Type, o.STI, o.MID, o.IPs, o.Assigned}
}

func (o *deviceIPs) UpdateValues() []interface{} {
	return []interface{}{o.Tag, o.Note, o.USR, o.TS, o.TID, o.Hostname, o.SerialNo, o.AssetTag, o.Make, o.Model, o.DTI, o.Rack, o.RU, o.Profile, o.Site, o.RID, o.Height, o.Mgmt, o.Alias, o.Type, o.STI, o.MID, o.IPs, o.Assigned, o.DID}
}

func (o *deviceIPs) MemberPointers() []interface{} {
	return []interface{}{&o.DID, &o.Tag, &o.Note, &o.USR, &o.TS, &o.TID, &o.Hostname, &o.SerialNo, &o.AssetTag, &o.Make, &o.Model, &o.DTI, &o.Rack, &o.RU, &o.Profile, &o.Site, &o.RID, &o.Height, &o.Mgmt, &o.Alias, &o.Type, &o.STI, &o.MID, &o.IPs, &o.Assigned}
}

func (o *deviceIPs) Key() int64 {
	return o.DID
}

func (o *deviceIPs) SetID(id int64) {
	o.DID = id
}

func (o *deviceIPs) TableName() string {
	return "devices_list"
}

func (o *deviceIPs) SelectFields() string {
	return "did,tag,note,usr,ts,tid,hostname,sn,asset_tag,make,model,dti,rack,ru,profile,site,rid,height,mgmt,alias,devtype,sti,mid,ips,assigned"
}

func (o *deviceIPs) InsertFields() string {
	return "did,tag,note,usr,ts,tid,hostname,sn,asset_tag,make,model,dti,rack,ru,profile,site,rid,height,mgmt,alias,devtype,sti,mid,ips,assigned"
}

func (o *deviceIPs) KeyField() string {
	return "did"
}

func (o *deviceIPs) KeyName() string {
	return "DID"
}

func (o *deviceIPs) Names() []string {
	return []string{"Tag", "Note", "USR", "TS", "TID", "Hostname", "SerialNo", "AssetTag", "Make", "Model", "DTI", "Rack", "RU", "Profile", "Site", "RID", "Height", "Mgmt", "Alias", "Type", "STI", "MID", "IPs", "Assigned"}
}

func (o *deviceIPs) ModifiedBy(user int64, t time.Time) {
}

//
// deviceAdjust DBObject generator
//
func (o deviceAdjust) NewObj() interface{} {
	return new(deviceAdjust)
}

//
// deviceAdjust DBObject interface functions
//
func (o *deviceAdjust) InsertValues() []interface{} {
	return []interface{}{o.RID, o.RU, o.Height}
}

func (o *deviceAdjust) UpdateValues() []interface{} {
	return []interface{}{o.RID, o.RU, o.Height, o.DID}
}

func (o *deviceAdjust) MemberPointers() []interface{} {
	return []interface{}{&o.DID, &o.RID, &o.RU, &o.Height}
}

func (o *deviceAdjust) Key() int64 {
	return o.DID
}

func (o *deviceAdjust) SetID(id int64) {
	o.DID = id
}

func (o *deviceAdjust) TableName() string {
	return "devices_adjust"
}

func (o *deviceAdjust) SelectFields() string {
	return "did,rid,ru,height"
}

func (o *deviceAdjust) InsertFields() string {
	return "did,rid,ru,height"
}

func (o *deviceAdjust) KeyField() string {
	return "did"
}

func (o *deviceAdjust) KeyName() string {
	return "DID"
}

func (o *deviceAdjust) Names() []string {
	return []string{"RID", "RU", "Height"}
}

func (o *deviceAdjust) ModifiedBy(user int64, t time.Time) {
}

//
// iface DBObject generator
//
func (o iface) NewObj() interface{} {
	return new(iface)
}

//
// iface DBObject interface functions
//
func (o *iface) InsertValues() []interface{} {
	return []interface{}{o.DID, o.Mgmt, o.Port, o.MAC, o.CableTag, o.SwitchPort}
}

func (o *iface) UpdateValues() []interface{} {
	return []interface{}{o.DID, o.Mgmt, o.Port, o.MAC, o.CableTag, o.SwitchPort, o.IFD}
}

func (o *iface) MemberPointers() []interface{} {
	return []interface{}{&o.IFD, &o.DID, &o.Mgmt, &o.Port, &o.MAC, &o.CableTag, &o.SwitchPort}
}

func (o *iface) Key() int64 {
	return o.IFD
}

func (o *iface) SetID(id int64) {
	o.IFD = id
}

func (o *iface) TableName() string {
	return "interfaces"
}

func (o *iface) SelectFields() string {
	return "ifd,did,mgmt,port,mac,cable_tag,switch_port"
}

func (o *iface) InsertFields() string {
	return "ifd,did,mgmt,port,mac,cable_tag,switch_port"
}

func (o *iface) KeyField() string {
	return "ifd"
}

func (o *iface) KeyName() string {
	return "IFD"
}

func (o *iface) Names() []string {
	return []string{"DID", "Mgmt", "Port", "MAC", "CableTag", "SwitchPort"}
}

func (o *iface) ModifiedBy(user int64, t time.Time) {
}

//
// ifaceView DBObject generator
//
func (o ifaceView) NewObj() interface{} {
	return new(ifaceView)
}

//
// ifaceView DBObject interface functions
//
func (o *ifaceView) InsertValues() []interface{} {
	return []interface{}{o.Port, o.ipType, o.SwitchPort, o.IPT, o.IID, o.IP32, o.Mgmt, o.IP, o.MAC, o.CableTag, o.DID}
}

func (o *ifaceView) UpdateValues() []interface{} {
	return []interface{}{o.Port, o.ipType, o.SwitchPort, o.IPT, o.IID, o.IP32, o.Mgmt, o.IP, o.MAC, o.CableTag, o.DID, o.IFD}
}

func (o *ifaceView) MemberPointers() []interface{} {
	return []interface{}{&o.IFD, &o.Port, &o.ipType, &o.SwitchPort, &o.IPT, &o.IID, &o.IP32, &o.Mgmt, &o.IP, &o.MAC, &o.CableTag, &o.DID}
}

func (o *ifaceView) Key() int64 {
	return o.IFD
}

func (o *ifaceView) SetID(id int64) {
	o.IFD = id
}

func (o *ifaceView) TableName() string {
	return "interfaces_view"
}

func (o *ifaceView) SelectFields() string {
	return "ifd,port,iptype,switch_port,ipt,iid,ip32,mgmt,ipv4,mac,cable_tag,did"
}

func (o *ifaceView) InsertFields() string {
	return "ifd,port,iptype,switch_port,ipt,iid,ip32,mgmt,ipv4,mac,cable_tag,did"
}

func (o *ifaceView) KeyField() string {
	return "ifd"
}

func (o *ifaceView) KeyName() string {
	return "IFD"
}

func (o *ifaceView) Names() []string {
	return []string{"Port", "ipType", "SwitchPort", "IPT", "IID", "IP32", "Mgmt", "IP", "MAC", "CableTag", "DID"}
}

func (o *ifaceView) ModifiedBy(user int64, t time.Time) {
}

//
// ipAddr DBObject generator
//
func (o ipAddr) NewObj() interface{} {
	return new(ipAddr)
}

//
// ipAddr DBObject interface functions
//
func (o *ipAddr) InsertValues() []interface{} {
	return []interface{}{o.TS, o.IP32, o.Note, o.USR, o.IPT, o.IP, o.IFD, o.VMI, o.VLI}
}

func (o *ipAddr) UpdateValues() []interface{} {
	return []interface{}{o.TS, o.IP32, o.Note, o.USR, o.IPT, o.IP, o.IFD, o.VMI, o.VLI, o.IID}
}

func (o *ipAddr) MemberPointers() []interface{} {
	return []interface{}{&o.IID, &o.TS, &o.IP32, &o.Note, &o.USR, &o.IPT, &o.IP, &o.IFD, &o.VMI, &o.VLI}
}

func (o *ipAddr) Key() int64 {
	return o.IID
}

func (o *ipAddr) SetID(id int64) {
	o.IID = id
}

func (o *ipAddr) TableName() string {
	return "ips"
}

func (o *ipAddr) SelectFields() string {
	return "iid,ts,ip32,note,usr,ipt,ipv4,ifd,vmi,vli"
}

func (o *ipAddr) InsertFields() string {
	return "iid,ts,ip32,note,usr,ipt,ipv4,ifd,vmi,vli"
}

func (o *ipAddr) KeyField() string {
	return "iid"
}

func (o *ipAddr) KeyName() string {
	return "IID"
}

func (o *ipAddr) Names() []string {
	return []string{"TS", "IP32", "Note", "USR", "IPT", "IP", "IFD", "VMI", "VLI"}
}

func (o *ipAddr) ModifiedBy(user int64, t time.Time) {
}

//
// ipView DBObject generator
//
func (o ipView) NewObj() interface{} {
	return new(ipView)
}

//
// ipView DBObject interface functions
//
func (o *ipView) InsertValues() []interface{} {
	return []interface{}{o.VLI, o.IPT, o.IP32, o.Type, o.Note, o.USR, o.IFD, o.IP, o.VLAN, o.TS, o.VMI}
}

func (o *ipView) UpdateValues() []interface{} {
	return []interface{}{o.VLI, o.IPT, o.IP32, o.Type, o.Note, o.USR, o.IFD, o.IP, o.VLAN, o.TS, o.VMI, o.IID}
}

func (o *ipView) MemberPointers() []interface{} {
	return []interface{}{&o.IID, &o.VLI, &o.IPT, &o.IP32, &o.Type, &o.Note, &o.USR, &o.IFD, &o.IP, &o.VLAN, &o.TS, &o.VMI}
}

func (o *ipView) Key() int64 {
	return o.IID
}

func (o *ipView) SetID(id int64) {
	o.IID = id
}

func (o *ipView) TableName() string {
	return "ips_view"
}

func (o *ipView) SelectFields() string {
	return "iid,vli,ipt,ip32,iptype,note,usr,ifd,ipv4,vlan,ts,vmi"
}

func (o *ipView) InsertFields() string {
	return "iid,vli,ipt,ip32,iptype,note,usr,ifd,ipv4,vlan,ts,vmi"
}

func (o *ipView) KeyField() string {
	return "iid"
}

func (o *ipView) KeyName() string {
	return "IID"
}

func (o *ipView) Names() []string {
	return []string{"VLI", "IPT", "IP32", "Type", "Note", "USR", "IFD", "IP", "VLAN", "TS", "VMI"}
}

func (o *ipView) ModifiedBy(user int64, t time.Time) {
}

//
// ipsUsed DBObject generator
//
func (o ipsUsed) NewObj() interface{} {
	return new(ipsUsed)
}

//
// ipsUsed DBObject interface functions
//
func (o *ipsUsed) InsertValues() []interface{} {
	return []interface{}{o.IP, o.Type, o.Host, o.STI, o.IPT, o.Rack, o.Hostname, o.Note, o.ID, o.RID, o.Site}
}

func (o *ipsUsed) UpdateValues() []interface{} {
	return []interface{}{o.IP, o.Type, o.Host, o.STI, o.IPT, o.Rack, o.Hostname, o.Note, o.ID, o.RID, o.Site}
}

func (o *ipsUsed) MemberPointers() []interface{} {
	return []interface{}{&o.IP, &o.Type, &o.Host, &o.STI, &o.IPT, &o.Rack, &o.Hostname, &o.Note, &o.ID, &o.RID, &o.Site}
}

func (o *ipsUsed) Key() int64 {
	return 0
}

func (o *ipsUsed) SetID(id int64) {
}

func (o *ipsUsed) TableName() string {
	return "ips_list"
}

func (o *ipsUsed) SelectFields() string {
	return "ip,iptype,host,sti,ipt,rack,hostname,note,id,rid,site"
}

func (o *ipsUsed) InsertFields() string {
	return "ip,iptype,host,sti,ipt,rack,hostname,note,id,rid,site"
}

func (o *ipsUsed) KeyField() string {
	return ""
}

func (o *ipsUsed) KeyName() string {
	return ""
}

func (o *ipsUsed) Names() []string {
	return []string{"IP", "Type", "Host", "STI", "IPT", "Rack", "Hostname", "Note", "ID", "RID", "Site"}
}

func (o *ipsUsed) ModifiedBy(user int64, t time.Time) {
}

//
// ipReserve DBObject generator
//
func (o ipReserve) NewObj() interface{} {
	return new(ipReserve)
}

//
// ipReserve DBObject interface functions
//
func (o *ipReserve) InsertValues() []interface{} {
	return []interface{}{o.Site, o.VLAN, o.IP32, o.Note, o.User, o.USR, o.VLI, o.IPT, o.IP, o.TS, o.STI}
}

func (o *ipReserve) UpdateValues() []interface{} {
	return []interface{}{o.Site, o.VLAN, o.IP32, o.Note, o.User, o.USR, o.VLI, o.IPT, o.IP, o.TS, o.STI, o.IID}
}

func (o *ipReserve) MemberPointers() []interface{} {
	return []interface{}{&o.IID, &o.Site, &o.VLAN, &o.IP32, &o.Note, &o.User, &o.USR, &o.VLI, &o.IPT, &o.IP, &o.TS, &o.STI}
}

func (o *ipReserve) Key() int64 {
	return o.IID
}

func (o *ipReserve) SetID(id int64) {
	o.IID = id
}

func (o *ipReserve) TableName() string {
	return "ips_reserved"
}

func (o *ipReserve) SelectFields() string {
	return "iid,site,vlan,ip32,note,username,usr,vli,ipt,ipv4,ts,sti"
}

func (o *ipReserve) InsertFields() string {
	return "iid,site,vlan,ip32,note,username,usr,vli,ipt,ipv4,ts,sti"
}

func (o *ipReserve) KeyField() string {
	return "iid"
}

func (o *ipReserve) KeyName() string {
	return "IID"
}

func (o *ipReserve) Names() []string {
	return []string{"Site", "VLAN", "IP32", "Note", "User", "USR", "VLI", "IPT", "IP", "TS", "STI"}
}

func (o *ipReserve) ModifiedBy(user int64, t time.Time) {
}

//
// provider DBObject generator
//
func (o provider) NewObj() interface{} {
	return new(provider)
}

//
// provider DBObject interface functions
//
func (o *provider) InsertValues() []interface{} {
	return []interface{}{o.Name, o.Contact, o.Phone, o.EMail, o.URL, o.Note}
}

func (o *provider) UpdateValues() []interface{} {
	return []interface{}{o.Name, o.Contact, o.Phone, o.EMail, o.URL, o.Note, o.PRI}
}

func (o *provider) MemberPointers() []interface{} {
	return []interface{}{&o.PRI, &o.Name, &o.Contact, &o.Phone, &o.EMail, &o.URL, &o.Note}
}

func (o *provider) Key() int64 {
	return o.PRI
}

func (o *provider) SetID(id int64) {
	o.PRI = id
}

func (o *provider) TableName() string {
	return "providers"
}

func (o *provider) SelectFields() string {
	return "pri,name,provider,a_side_xcon,a_side_handoff,z_side_xcon,note"
}

func (o *provider) InsertFields() string {
	return "pri,name,provider,a_side_xcon,a_side_handoff,z_side_xcon,note"
}

func (o *provider) KeyField() string {
	return "pri"
}

func (o *provider) KeyName() string {
	return "PRI"
}

func (o *provider) Names() []string {
	return []string{"Name", "Contact", "Phone", "EMail", "URL", "Note"}
}

func (o *provider) ModifiedBy(user int64, t time.Time) {
}

//
// circuit DBObject generator
//
func (o circuit) NewObj() interface{} {
	return new(circuit)
}

//
// circuit DBObject interface functions
//
func (o *circuit) InsertValues() []interface{} {
	return []interface{}{o.ASideHandoff, o.ZSideXConn, o.ZSideHandoff, o.Note, o.STI, o.PRI, o.CircuitID, o.ASideXConn}
}

func (o *circuit) UpdateValues() []interface{} {
	return []interface{}{o.ASideHandoff, o.ZSideXConn, o.ZSideHandoff, o.Note, o.STI, o.PRI, o.CircuitID, o.ASideXConn, o.CID}
}

func (o *circuit) MemberPointers() []interface{} {
	return []interface{}{&o.CID, &o.ASideHandoff, &o.ZSideXConn, &o.ZSideHandoff, &o.Note, &o.STI, &o.PRI, &o.CircuitID, &o.ASideXConn}
}

func (o *circuit) Key() int64 {
	return o.CID
}

func (o *circuit) SetID(id int64) {
	o.CID = id
}

func (o *circuit) TableName() string {
	return "circuits"
}

func (o *circuit) SelectFields() string {
	return "cid,a_side_handoff,z_side_xcon,z_side_handoff,note,site,pri,circuit_id,a_side_xcon"
}

func (o *circuit) InsertFields() string {
	return "cid,a_side_handoff,z_side_xcon,z_side_handoff,note,site,pri,circuit_id,a_side_xcon"
}

func (o *circuit) KeyField() string {
	return "cid"
}

func (o *circuit) KeyName() string {
	return "CID"
}

func (o *circuit) Names() []string {
	return []string{"ASideHandoff", "ZSideXConn", "ZSideHandoff", "Note", "STI", "PRI", "CircuitID", "ASideXConn"}
}

func (o *circuit) ModifiedBy(user int64, t time.Time) {
}

//
// circuitView DBObject generator
//
func (o circuitView) NewObj() interface{} {
	return new(circuitView)
}

//
// circuitView DBObject interface functions
//
func (o *circuitView) InsertValues() []interface{} {
	return []interface{}{o.PRI, o.Site, o.Provider, o.ZSideXConn, o.ZSideHandoff, o.Note, o.STI, o.CircuitID, o.ASideXConn, o.ASideHandoff}
}

func (o *circuitView) UpdateValues() []interface{} {
	return []interface{}{o.PRI, o.Site, o.Provider, o.ZSideXConn, o.ZSideHandoff, o.Note, o.STI, o.CircuitID, o.ASideXConn, o.ASideHandoff, o.CID}
}

func (o *circuitView) MemberPointers() []interface{} {
	return []interface{}{&o.CID, &o.PRI, &o.Site, &o.Provider, &o.ZSideXConn, &o.ZSideHandoff, &o.Note, &o.STI, &o.CircuitID, &o.ASideXConn, &o.ASideHandoff}
}

func (o *circuitView) Key() int64 {
	return o.CID
}

func (o *circuitView) SetID(id int64) {
	o.CID = id
}

func (o *circuitView) TableName() string {
	return "circuits"
}

func (o *circuitView) SelectFields() string {
	return "cid,pri,site,provider,z_side_xcon,z_side_handoff,note,site,circuit_id,a_side_xcon,a_side_handoff"
}

func (o *circuitView) InsertFields() string {
	return "cid,pri,site,provider,z_side_xcon,z_side_handoff,note,site,circuit_id,a_side_xcon,a_side_handoff"
}

func (o *circuitView) KeyField() string {
	return "cid"
}

func (o *circuitView) KeyName() string {
	return "CID"
}

func (o *circuitView) Names() []string {
	return []string{"PRI", "Site", "Provider", "ZSideXConn", "ZSideHandoff", "Note", "STI", "CircuitID", "ASideXConn", "ASideHandoff"}
}

func (o *circuitView) ModifiedBy(user int64, t time.Time) {
}

//
// subCircuit DBObject generator
//
func (o subCircuit) NewObj() interface{} {
	return new(subCircuit)
}

//
// subCircuit DBObject interface functions
//
func (o *subCircuit) InsertValues() []interface{} {
	return []interface{}{o.CID, o.SubID, o.Note}
}

func (o *subCircuit) UpdateValues() []interface{} {
	return []interface{}{o.CID, o.SubID, o.Note, o.SCI}
}

func (o *subCircuit) MemberPointers() []interface{} {
	return []interface{}{&o.SCI, &o.CID, &o.SubID, &o.Note}
}

func (o *subCircuit) Key() int64 {
	return o.SCI
}

func (o *subCircuit) SetID(id int64) {
	o.SCI = id
}

func (o *subCircuit) TableName() string {
	return "sub_circuits"
}

func (o *subCircuit) SelectFields() string {
	return "sci,cid,sub_circuit_id,note"
}

func (o *subCircuit) InsertFields() string {
	return "sci,cid,sub_circuit_id,note"
}

func (o *subCircuit) KeyField() string {
	return "sci"
}

func (o *subCircuit) KeyName() string {
	return "SCI"
}

func (o *subCircuit) Names() []string {
	return []string{"CID", "SubID", "Note"}
}

func (o *subCircuit) ModifiedBy(user int64, t time.Time) {
}

//
// circuitList DBObject generator
//
func (o circuitList) NewObj() interface{} {
	return new(circuitList)
}

//
// circuitList DBObject interface functions
//
func (o *circuitList) InsertValues() []interface{} {
	return []interface{}{o.STI, o.Provider, o.CircuitID, o.ASideXConn, o.ZSideXConn, o.SubNote, o.PRI, o.Site, o.SubID, o.ASideHandoff, o.ZSideHandoff, o.Note}
}

func (o *circuitList) UpdateValues() []interface{} {
	return []interface{}{o.STI, o.Provider, o.CircuitID, o.ASideXConn, o.ZSideXConn, o.SubNote, o.PRI, o.Site, o.SubID, o.ASideHandoff, o.ZSideHandoff, o.Note, o.CID}
}

func (o *circuitList) MemberPointers() []interface{} {
	return []interface{}{&o.CID, &o.STI, &o.Provider, &o.CircuitID, &o.ASideXConn, &o.ZSideXConn, &o.SubNote, &o.PRI, &o.Site, &o.SubID, &o.ASideHandoff, &o.ZSideHandoff, &o.Note}
}

func (o *circuitList) Key() int64 {
	return o.CID
}

func (o *circuitList) SetID(id int64) {
	o.CID = id
}

func (o *circuitList) TableName() string {
	return "circuits"
}

func (o *circuitList) SelectFields() string {
	return "cid,site,provider,circuit_id,a_side_xcon,z_side_xcon,sub_note,pri,site,sub_circuit_id,a_side_handoff,z_side_handoff,note"
}

func (o *circuitList) InsertFields() string {
	return "cid,site,provider,circuit_id,a_side_xcon,z_side_xcon,sub_note,pri,site,sub_circuit_id,a_side_handoff,z_side_handoff,note"
}

func (o *circuitList) KeyField() string {
	return "cid"
}

func (o *circuitList) KeyName() string {
	return "CID"
}

func (o *circuitList) Names() []string {
	return []string{"STI", "Provider", "CircuitID", "ASideXConn", "ZSideXConn", "SubNote", "PRI", "Site", "SubID", "ASideHandoff", "ZSideHandoff", "Note"}
}

func (o *circuitList) ModifiedBy(user int64, t time.Time) {
}

//
// vlanProfile DBObject generator
//
func (o vlanProfile) NewObj() interface{} {
	return new(vlanProfile)
}

//
// vlanProfile DBObject interface functions
//
func (o *vlanProfile) InsertValues() []interface{} {
	return []interface{}{o.Name}
}

func (o *vlanProfile) UpdateValues() []interface{} {
	return []interface{}{o.Name, o.VPID}
}

func (o *vlanProfile) MemberPointers() []interface{} {
	return []interface{}{&o.VPID, &o.Name}
}

func (o *vlanProfile) Key() int64 {
	return o.VPID
}

func (o *vlanProfile) SetID(id int64) {
	o.VPID = id
}

func (o *vlanProfile) TableName() string {
	return "vlan_profiles"
}

func (o *vlanProfile) SelectFields() string {
	return "vpid,name"
}

func (o *vlanProfile) InsertFields() string {
	return "vpid,name"
}

func (o *vlanProfile) KeyField() string {
	return "vpid"
}

func (o *vlanProfile) KeyName() string {
	return "VPID"
}

func (o *vlanProfile) Names() []string {
	return []string{"Name"}
}

func (o *vlanProfile) ModifiedBy(user int64, t time.Time) {
}

//
// vlan DBObject generator
//
func (o vlan) NewObj() interface{} {
	return new(vlan)
}

//
// vlan DBObject interface functions
//
func (o *vlan) InsertValues() []interface{} {
	return []interface{}{o.STI, o.Name, o.Gateway, o.USR, o.Profile, o.Route, o.Netmask, o.Starting, o.Note, o.TS}
}

func (o *vlan) UpdateValues() []interface{} {
	return []interface{}{o.STI, o.Name, o.Gateway, o.USR, o.Profile, o.Route, o.Netmask, o.Starting, o.Note, o.TS, o.VLI}
}

func (o *vlan) MemberPointers() []interface{} {
	return []interface{}{&o.VLI, &o.STI, &o.Name, &o.Gateway, &o.USR, &o.Profile, &o.Route, &o.Netmask, &o.Starting, &o.Note, &o.TS}
}

func (o *vlan) Key() int64 {
	return o.VLI
}

func (o *vlan) SetID(id int64) {
	o.VLI = id
}

func (o *vlan) TableName() string {
	return "vlans"
}

func (o *vlan) SelectFields() string {
	return "vli,sti,name,gateway,usr,profile,route,netmask,starting,note,ts"
}

func (o *vlan) InsertFields() string {
	return "vli,sti,name,gateway,usr,profile,route,netmask,starting,note,ts"
}

func (o *vlan) KeyField() string {
	return "vli"
}

func (o *vlan) KeyName() string {
	return "VLI"
}

func (o *vlan) Names() []string {
	return []string{"STI", "Name", "Gateway", "USR", "Profile", "Route", "Netmask", "Starting", "Note", "TS"}
}

func (o *vlan) ModifiedBy(user int64, t time.Time) {
	o.USR = &user
	o.TS = t
}

//
// vlanView DBObject generator
//
func (o vlanView) NewObj() interface{} {
	return new(vlanView)
}

//
// vlanView DBObject interface functions
//
func (o *vlanView) InsertValues() []interface{} {
	return []interface{}{o.Note, o.USR, o.Site, o.Netmask, o.Starting, o.Gateway, o.Route, o.TS, o.STI, o.Name, o.Profile}
}

func (o *vlanView) UpdateValues() []interface{} {
	return []interface{}{o.Note, o.USR, o.Site, o.Netmask, o.Starting, o.Gateway, o.Route, o.TS, o.STI, o.Name, o.Profile, o.VLI}
}

func (o *vlanView) MemberPointers() []interface{} {
	return []interface{}{&o.VLI, &o.Note, &o.USR, &o.Site, &o.Netmask, &o.Starting, &o.Gateway, &o.Route, &o.TS, &o.STI, &o.Name, &o.Profile}
}

func (o *vlanView) Key() int64 {
	return o.VLI
}

func (o *vlanView) SetID(id int64) {
	o.VLI = id
}

func (o *vlanView) TableName() string {
	return "vlans_view"
}

func (o *vlanView) SelectFields() string {
	return "vli,note,usr,site,netmask,starting,gateway,route,ts,sti,name,profile"
}

func (o *vlanView) InsertFields() string {
	return "vli,note,usr,site,netmask,starting,gateway,route,ts,sti,name,profile"
}

func (o *vlanView) KeyField() string {
	return "vli"
}

func (o *vlanView) KeyName() string {
	return "VLI"
}

func (o *vlanView) Names() []string {
	return []string{"Note", "USR", "Site", "Netmask", "Starting", "Gateway", "Route", "TS", "STI", "Name", "Profile"}
}

func (o *vlanView) ModifiedBy(user int64, t time.Time) {
	o.USR = &user
	o.TS = t
}

//
// pxeDevice DBObject generator
//
func (o pxeDevice) NewObj() interface{} {
	return new(pxeDevice)
}

//
// pxeDevice DBObject interface functions
//
func (o *pxeDevice) InsertValues() []interface{} {
	return []interface{}{o.STI, o.Site, o.RU, o.RID, o.Rack, o.Hostname, o.Profile, o.MAC, o.IP, o.IPMI, o.Note}
}

func (o *pxeDevice) UpdateValues() []interface{} {
	return []interface{}{o.STI, o.Site, o.RU, o.RID, o.Rack, o.Hostname, o.Profile, o.MAC, o.IP, o.IPMI, o.Note, o.DID}
}

func (o *pxeDevice) MemberPointers() []interface{} {
	return []interface{}{&o.DID, &o.STI, &o.Site, &o.RU, &o.RID, &o.Rack, &o.Hostname, &o.Profile, &o.MAC, &o.IP, &o.IPMI, &o.Note}
}

func (o *pxeDevice) Key() int64 {
	return o.DID
}

func (o *pxeDevice) SetID(id int64) {
	o.DID = id
}

func (o *pxeDevice) TableName() string {
	return "pxedevice"
}

func (o *pxeDevice) SelectFields() string {
	return "did,sti,site,ru,rid,rack,hostname,profile,mac,ip,ipmi,note"
}

func (o *pxeDevice) InsertFields() string {
	return "did,sti,site,ru,rid,rack,hostname,profile,mac,ip,ipmi,note"
}

func (o *pxeDevice) KeyField() string {
	return "did"
}

func (o *pxeDevice) KeyName() string {
	return "DID"
}

func (o *pxeDevice) Names() []string {
	return []string{"STI", "Site", "RU", "RID", "Rack", "Hostname", "Profile", "MAC", "IP", "IPMI", "Note"}
}

func (o *pxeDevice) ModifiedBy(user int64, t time.Time) {
}
