// generated by dbgen ; DO NOT EDIT

package main

import (
	"time"
)

//
// Hit DBObject generator
//
func (o Hit) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// Hit DBObject interface functions
//
func (o *Hit) InsertValues() []interface{} {
	return []interface{}{o.ID, o.Kind, o.Name}
}

func (o *Hit) UpdateValues() []interface{} {
	return []interface{}{o.ID, o.Kind, o.Name}
}

func (o *Hit) MemberPointers() []interface{} {
	return []interface{}{&o.ID, &o.Kind, &o.Name}
}

func (o *Hit) Key() int64 {
	return 0
}

func (o *Hit) SetID(id int64) {
}

func (o *Hit) TableName() string {
	return ""
}

func (o *Hit) SelectFields() string {
	return "id,kind,name"
}

func (o *Hit) InsertFields() string {
	return "id,kind,name"
}

func (o *Hit) KeyField() string {
	return ""
}

func (o *Hit) KeyName() string {
	return ""
}

func (o *Hit) Names() []string {
	return []string{"ID", "Kind", "Name"}
}

func (o *Hit) ModifiedBy(user int64, t time.Time) {
}

//
// Summary DBObject generator
//
func (o Summary) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// Summary DBObject interface functions
//
func (o *Summary) InsertValues() []interface{} {
	return []interface{}{o.Site, o.Servers, o.VMs}
}

func (o *Summary) UpdateValues() []interface{} {
	return []interface{}{o.Site, o.Servers, o.VMs, o.ID}
}

func (o *Summary) MemberPointers() []interface{} {
	return []interface{}{&o.ID, &o.Site, &o.Servers, &o.VMs}
}

func (o *Summary) Key() int64 {
	return o.ID
}

func (o *Summary) SetID(id int64) {
	o.ID = id
}

func (o *Summary) TableName() string {
	return "summary"
}

func (o *Summary) SelectFields() string {
	return "sti,site,servers,vms"
}

func (o *Summary) InsertFields() string {
	return "sti,site,servers,vms"
}

func (o *Summary) KeyField() string {
	return "sti"
}

func (o *Summary) KeyName() string {
	return "ID"
}

func (o *Summary) Names() []string {
	return []string{"Site", "Servers", "VMs"}
}

func (o *Summary) ModifiedBy(user int64, t time.Time) {
}

//
// User DBObject generator
//
func (o User) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// User DBObject interface functions
//
func (o *User) InsertValues() []interface{} {
	return []interface{}{o.APIKey, o.Level, o.Login, o.First, o.Last, o.Email}
}

func (o *User) UpdateValues() []interface{} {
	return []interface{}{o.APIKey, o.Level, o.Login, o.First, o.Last, o.Email, o.USR}
}

func (o *User) MemberPointers() []interface{} {
	return []interface{}{&o.USR, &o.APIKey, &o.Level, &o.Login, &o.First, &o.Last, &o.Email}
}

func (o *User) Key() int64 {
	return o.USR
}

func (o *User) SetID(id int64) {
	o.USR = id
}

func (o *User) TableName() string {
	return "users"
}

func (o *User) SelectFields() string {
	return "usr,apikey,admin,login,firstname,lastname,email"
}

func (o *User) InsertFields() string {
	return "usr,apikey,admin,login,firstname,lastname,email"
}

func (o *User) KeyField() string {
	return "usr"
}

func (o *User) KeyName() string {
	return "USR"
}

func (o *User) Names() []string {
	return []string{"APIKey", "Level", "Login", "First", "Last", "Email"}
}

func (o *User) ModifiedBy(user int64, t time.Time) {
}

//
// FullUser DBObject generator
//
func (o FullUser) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// FullUser DBObject interface functions
//
func (o *FullUser) InsertValues() []interface{} {
	return []interface{}{o.Level, o.Login, o.First, o.Last, o.Email, o.APIKey, o.Password, o.Salt}
}

func (o *FullUser) UpdateValues() []interface{} {
	return []interface{}{o.Level, o.Login, o.First, o.Last, o.Email, o.APIKey, o.Password, o.Salt, o.USR}
}

func (o *FullUser) MemberPointers() []interface{} {
	return []interface{}{&o.USR, &o.Level, &o.Login, &o.First, &o.Last, &o.Email, &o.APIKey, &o.Password, &o.Salt}
}

func (o *FullUser) Key() int64 {
	return o.USR
}

func (o *FullUser) SetID(id int64) {
	o.USR = id
}

func (o *FullUser) TableName() string {
	return "users"
}

func (o *FullUser) SelectFields() string {
	return "usr,admin,login,firstname,lastname,email,apikey,pw_hash,pw_salt"
}

func (o *FullUser) InsertFields() string {
	return "usr,admin,login,firstname,lastname,email,apikey,pw_hash,pw_salt"
}

func (o *FullUser) KeyField() string {
	return "usr"
}

func (o *FullUser) KeyName() string {
	return "USR"
}

func (o *FullUser) Names() []string {
	return []string{"Level", "Login", "First", "Last", "Email", "APIKey", "Password", "Salt"}
}

func (o *FullUser) ModifiedBy(user int64, t time.Time) {
}

//
// Vendor DBObject generator
//
func (o Vendor) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// Vendor DBObject interface functions
//
func (o *Vendor) InsertValues() []interface{} {
	return []interface{}{o.Phone, o.Address, o.City, o.State, o.Note, o.Modified, o.Name, o.WWW, o.Country, o.Postal, o.USR}
}

func (o *Vendor) UpdateValues() []interface{} {
	return []interface{}{o.Phone, o.Address, o.City, o.State, o.Note, o.Modified, o.Name, o.WWW, o.Country, o.Postal, o.USR, o.VID}
}

func (o *Vendor) MemberPointers() []interface{} {
	return []interface{}{&o.VID, &o.Phone, &o.Address, &o.City, &o.State, &o.Note, &o.Modified, &o.Name, &o.WWW, &o.Country, &o.Postal, &o.USR}
}

func (o *Vendor) Key() int64 {
	return o.VID
}

func (o *Vendor) SetID(id int64) {
	o.VID = id
}

func (o *Vendor) TableName() string {
	return "vendors"
}

func (o *Vendor) SelectFields() string {
	return "vid,phone,address,city,state,note,ts,name,www,country,postal,usr"
}

func (o *Vendor) InsertFields() string {
	return "vid,phone,address,city,state,note,ts,name,www,country,postal,usr"
}

func (o *Vendor) KeyField() string {
	return "vid"
}

func (o *Vendor) KeyName() string {
	return "VID"
}

func (o *Vendor) Names() []string {
	return []string{"Phone", "Address", "City", "State", "Note", "Modified", "Name", "WWW", "Country", "Postal", "USR"}
}

func (o *Vendor) ModifiedBy(user int64, t time.Time) {
	o.USR = user
	o.Modified = t
}

//
// IPType DBObject generator
//
func (o IPType) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// IPType DBObject interface functions
//
func (o *IPType) InsertValues() []interface{} {
	return []interface{}{o.Name, o.Multi}
}

func (o *IPType) UpdateValues() []interface{} {
	return []interface{}{o.Name, o.Multi, o.IPT}
}

func (o *IPType) MemberPointers() []interface{} {
	return []interface{}{&o.IPT, &o.Name, &o.Multi}
}

func (o *IPType) Key() int64 {
	return o.IPT
}

func (o *IPType) SetID(id int64) {
	o.IPT = id
}

func (o *IPType) TableName() string {
	return "ip_types"
}

func (o *IPType) SelectFields() string {
	return "ipt,name,multi"
}

func (o *IPType) InsertFields() string {
	return "ipt,name,multi"
}

func (o *IPType) KeyField() string {
	return "ipt"
}

func (o *IPType) KeyName() string {
	return "IPT"
}

func (o *IPType) Names() []string {
	return []string{"Name", "Multi"}
}

func (o *IPType) ModifiedBy(user int64, t time.Time) {
}

//
// RMA DBObject generator
//
func (o RMA) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// RMA DBObject interface functions
//
func (o *RMA) InsertValues() []interface{} {
	return []interface{}{o.OldPID, o.Jira, o.DCTicket, o.Shipped, o.DID, o.RecvTrack, o.Received, o.USR, o.VendorRMA, o.ShipTrack, o.Receiving, o.Created, o.STI, o.VID, o.NewPID, o.Note, o.Closed}
}

func (o *RMA) UpdateValues() []interface{} {
	return []interface{}{o.OldPID, o.Jira, o.DCTicket, o.Shipped, o.DID, o.RecvTrack, o.Received, o.USR, o.VendorRMA, o.ShipTrack, o.Receiving, o.Created, o.STI, o.VID, o.NewPID, o.Note, o.Closed, o.RMD}
}

func (o *RMA) MemberPointers() []interface{} {
	return []interface{}{&o.RMD, &o.OldPID, &o.Jira, &o.DCTicket, &o.Shipped, &o.DID, &o.RecvTrack, &o.Received, &o.USR, &o.VendorRMA, &o.ShipTrack, &o.Receiving, &o.Created, &o.STI, &o.VID, &o.NewPID, &o.Note, &o.Closed}
}

func (o *RMA) Key() int64 {
	return o.RMD
}

func (o *RMA) SetID(id int64) {
	o.RMD = id
}

func (o *RMA) TableName() string {
	return "rmas"
}

func (o *RMA) SelectFields() string {
	return "rmd,old_pid,jira,dc_ticket,date_shipped,did,recv_tracking,date_received,usr,vendor_rma,ship_tracking,dc_receiving,date_created,sti,vid,new_pid,note,date_closed"
}

func (o *RMA) InsertFields() string {
	return "rmd,old_pid,jira,dc_ticket,date_shipped,did,recv_tracking,date_received,usr,vendor_rma,ship_tracking,dc_receiving,date_created,sti,vid,new_pid,note,date_closed"
}

func (o *RMA) KeyField() string {
	return "rmd"
}

func (o *RMA) KeyName() string {
	return "RMD"
}

func (o *RMA) Names() []string {
	return []string{"OldPID", "Jira", "DCTicket", "Shipped", "DID", "RecvTrack", "Received", "USR", "VendorRMA", "ShipTrack", "Receiving", "Created", "STI", "VID", "NewPID", "Note", "Closed"}
}

func (o *RMA) ModifiedBy(user int64, t time.Time) {
}

//
// RMAView DBObject generator
//
func (o RMAView) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// RMAView DBObject interface functions
//
func (o *RMAView) InsertValues() []interface{} {
	return []interface{}{o.VendorRMA, o.DCTicket, o.OldPID, o.PartNumber, o.RecvTrack, o.Note, o.USR, o.NewPID, o.Hostname, o.Site, o.DeviceSN, o.PartSN, o.ShipTrack, o.Receiving, o.Shipped, o.STI, o.DID, o.Jira, o.Received, o.Closed, o.Created, o.VID, o.Description}
}

func (o *RMAView) UpdateValues() []interface{} {
	return []interface{}{o.VendorRMA, o.DCTicket, o.OldPID, o.PartNumber, o.RecvTrack, o.Note, o.USR, o.NewPID, o.Hostname, o.Site, o.DeviceSN, o.PartSN, o.ShipTrack, o.Receiving, o.Shipped, o.STI, o.DID, o.Jira, o.Received, o.Closed, o.Created, o.VID, o.Description, o.RMD}
}

func (o *RMAView) MemberPointers() []interface{} {
	return []interface{}{&o.RMD, &o.VendorRMA, &o.DCTicket, &o.OldPID, &o.PartNumber, &o.RecvTrack, &o.Note, &o.USR, &o.NewPID, &o.Hostname, &o.Site, &o.DeviceSN, &o.PartSN, &o.ShipTrack, &o.Receiving, &o.Shipped, &o.STI, &o.DID, &o.Jira, &o.Received, &o.Closed, &o.Created, &o.VID, &o.Description}
}

func (o *RMAView) Key() int64 {
	return o.RMD
}

func (o *RMAView) SetID(id int64) {
	o.RMD = id
}

func (o *RMAView) TableName() string {
	return "rmas_view"
}

func (o *RMAView) SelectFields() string {
	return "rmd,vendor_rma,dc_ticket,old_pid,part_no,recv_tracking,note,usr,new_pid,hostname,site,device_sn,part_sn,ship_tracking,dc_receiving,date_shipped,sti,did,jira,date_received,date_closed,date_created,vid,description"
}

func (o *RMAView) InsertFields() string {
	return "rmd,vendor_rma,dc_ticket,old_pid,part_no,recv_tracking,note,usr,new_pid,hostname,site,device_sn,part_sn,ship_tracking,dc_receiving,date_shipped,sti,did,jira,date_received,date_closed,date_created,vid,description"
}

func (o *RMAView) KeyField() string {
	return "rmd"
}

func (o *RMAView) KeyName() string {
	return "RMD"
}

func (o *RMAView) Names() []string {
	return []string{"VendorRMA", "DCTicket", "OldPID", "PartNumber", "RecvTrack", "Note", "USR", "NewPID", "Hostname", "Site", "DeviceSN", "PartSN", "ShipTrack", "Receiving", "Shipped", "STI", "DID", "Jira", "Received", "Closed", "Created", "VID", "Description"}
}

func (o *RMAView) ModifiedBy(user int64, t time.Time) {
}

//
// Manufacturer DBObject generator
//
func (o Manufacturer) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// Manufacturer DBObject interface functions
//
func (o *Manufacturer) InsertValues() []interface{} {
	return []interface{}{o.URL, o.USR, o.Modified, o.Name, o.Note, o.AKA}
}

func (o *Manufacturer) UpdateValues() []interface{} {
	return []interface{}{o.URL, o.USR, o.Modified, o.Name, o.Note, o.AKA, o.MID}
}

func (o *Manufacturer) MemberPointers() []interface{} {
	return []interface{}{&o.MID, &o.URL, &o.USR, &o.Modified, &o.Name, &o.Note, &o.AKA}
}

func (o *Manufacturer) Key() int64 {
	return o.MID
}

func (o *Manufacturer) SetID(id int64) {
	o.MID = id
}

func (o *Manufacturer) TableName() string {
	return "mfgrs"
}

func (o *Manufacturer) SelectFields() string {
	return "mid,url,usr,ts,name,note,aka"
}

func (o *Manufacturer) InsertFields() string {
	return "mid,url,usr,ts,name,note,aka"
}

func (o *Manufacturer) KeyField() string {
	return "mid"
}

func (o *Manufacturer) KeyName() string {
	return "MID"
}

func (o *Manufacturer) Names() []string {
	return []string{"URL", "USR", "Modified", "Name", "Note", "AKA"}
}

func (o *Manufacturer) ModifiedBy(user int64, t time.Time) {
	o.USR = user
	o.Modified = t
}

//
// PartType DBObject generator
//
func (o PartType) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// PartType DBObject interface functions
//
func (o *PartType) InsertValues() []interface{} {
	return []interface{}{o.Name, o.USR, o.Modified}
}

func (o *PartType) UpdateValues() []interface{} {
	return []interface{}{o.Name, o.USR, o.Modified, o.PTI}
}

func (o *PartType) MemberPointers() []interface{} {
	return []interface{}{&o.PTI, &o.Name, &o.USR, &o.Modified}
}

func (o *PartType) Key() int64 {
	return o.PTI
}

func (o *PartType) SetID(id int64) {
	o.PTI = id
}

func (o *PartType) TableName() string {
	return "part_types"
}

func (o *PartType) SelectFields() string {
	return "pti,name,usr,ts"
}

func (o *PartType) InsertFields() string {
	return "pti,name,usr,ts"
}

func (o *PartType) KeyField() string {
	return "pti"
}

func (o *PartType) KeyName() string {
	return "PTI"
}

func (o *PartType) Names() []string {
	return []string{"Name", "USR", "Modified"}
}

func (o *PartType) ModifiedBy(user int64, t time.Time) {
	o.USR = user
	o.Modified = t
}

//
// SKU DBObject generator
//
func (o SKU) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// SKU DBObject interface functions
//
func (o *SKU) InsertValues() []interface{} {
	return []interface{}{o.Description, o.SKU, o.USR, o.Modified, o.MID, o.PTI, o.PartNumber}
}

func (o *SKU) UpdateValues() []interface{} {
	return []interface{}{o.Description, o.SKU, o.USR, o.Modified, o.MID, o.PTI, o.PartNumber, o.KID}
}

func (o *SKU) MemberPointers() []interface{} {
	return []interface{}{&o.KID, &o.Description, &o.SKU, &o.USR, &o.Modified, &o.MID, &o.PTI, &o.PartNumber}
}

func (o *SKU) Key() int64 {
	return o.KID
}

func (o *SKU) SetID(id int64) {
	o.KID = id
}

func (o *SKU) TableName() string {
	return "skus"
}

func (o *SKU) SelectFields() string {
	return "kid,description,sku,usr,ts,mid,pti,part_no"
}

func (o *SKU) InsertFields() string {
	return "kid,description,sku,usr,ts,mid,pti,part_no"
}

func (o *SKU) KeyField() string {
	return "kid"
}

func (o *SKU) KeyName() string {
	return "KID"
}

func (o *SKU) Names() []string {
	return []string{"Description", "SKU", "USR", "Modified", "MID", "PTI", "PartNumber"}
}

func (o *SKU) ModifiedBy(user int64, t time.Time) {
	o.USR = user
	o.Modified = t
}

//
// Part DBObject generator
//
func (o Part) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// Part DBObject interface functions
//
func (o *Part) InsertValues() []interface{} {
	return []interface{}{o.KID, o.Location, o.Serial, o.AssetTag, o.Unused, o.Bad, o.VID, o.DID, o.STI, o.Cents, o.USR, o.Modified}
}

func (o *Part) UpdateValues() []interface{} {
	return []interface{}{o.KID, o.Location, o.Serial, o.AssetTag, o.Unused, o.Bad, o.VID, o.DID, o.STI, o.Cents, o.USR, o.Modified, o.PID}
}

func (o *Part) MemberPointers() []interface{} {
	return []interface{}{&o.PID, &o.KID, &o.Location, &o.Serial, &o.AssetTag, &o.Unused, &o.Bad, &o.VID, &o.DID, &o.STI, &o.Cents, &o.USR, &o.Modified}
}

func (o *Part) Key() int64 {
	return o.PID
}

func (o *Part) SetID(id int64) {
	o.PID = id
}

func (o *Part) TableName() string {
	return "parts"
}

func (o *Part) SelectFields() string {
	return "pid,kid,location,serial_no,asset_tag,unused,bad,vid,did,sti,cents,usr,ts"
}

func (o *Part) InsertFields() string {
	return "pid,kid,location,serial_no,asset_tag,unused,bad,vid,did,sti,cents,usr,ts"
}

func (o *Part) KeyField() string {
	return "pid"
}

func (o *Part) KeyName() string {
	return "PID"
}

func (o *Part) Names() []string {
	return []string{"KID", "Location", "Serial", "AssetTag", "Unused", "Bad", "VID", "DID", "STI", "Cents", "USR", "Modified"}
}

func (o *Part) ModifiedBy(user int64, t time.Time) {
	o.USR = user
	o.Modified = t
}

//
// PartView DBObject generator
//
func (o PartView) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// PartView DBObject interface functions
//
func (o *PartView) InsertValues() []interface{} {
	return []interface{}{o.RMD, o.Cents, o.Bad, o.SKU, o.Description, o.Unused, o.STI, o.Location, o.AssetTag, o.Price, o.VID, o.DID, o.PartType, o.Serial, o.PartNumber, o.Mfgr, o.Vendor, o.KID, o.Site, o.Hostname}
}

func (o *PartView) UpdateValues() []interface{} {
	return []interface{}{o.RMD, o.Cents, o.Bad, o.SKU, o.Description, o.Unused, o.STI, o.Location, o.AssetTag, o.Price, o.VID, o.DID, o.PartType, o.Serial, o.PartNumber, o.Mfgr, o.Vendor, o.KID, o.Site, o.Hostname, o.PID}
}

func (o *PartView) MemberPointers() []interface{} {
	return []interface{}{&o.PID, &o.RMD, &o.Cents, &o.Bad, &o.SKU, &o.Description, &o.Unused, &o.STI, &o.Location, &o.AssetTag, &o.Price, &o.VID, &o.DID, &o.PartType, &o.Serial, &o.PartNumber, &o.Mfgr, &o.Vendor, &o.KID, &o.Site, &o.Hostname}
}

func (o *PartView) Key() int64 {
	return o.PID
}

func (o *PartView) SetID(id int64) {
	o.PID = id
}

func (o *PartView) TableName() string {
	return "parts_view"
}

func (o *PartView) SelectFields() string {
	return "pid,rmd,cents,bad,sku,description,unused,sti,location,asset_tag,price,vid,did,part_type,serial_no,part_no,mfgr,vendor,kid,site,hostname"
}

func (o *PartView) InsertFields() string {
	return "pid,rmd,cents,bad,sku,description,unused,sti,location,asset_tag,price,vid,did,part_type,serial_no,part_no,mfgr,vendor,kid,site,hostname"
}

func (o *PartView) KeyField() string {
	return "pid"
}

func (o *PartView) KeyName() string {
	return "PID"
}

func (o *PartView) Names() []string {
	return []string{"RMD", "Cents", "Bad", "SKU", "Description", "Unused", "STI", "Location", "AssetTag", "Price", "VID", "DID", "PartType", "Serial", "PartNumber", "Mfgr", "Vendor", "KID", "Site", "Hostname"}
}

func (o *PartView) ModifiedBy(user int64, t time.Time) {
}

//
// Site DBObject generator
//
func (o Site) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// Site DBObject interface functions
//
func (o *Site) InsertValues() []interface{} {
	return []interface{}{o.Modified, o.Postal, o.Country, o.Web, o.State, o.Phone, o.USR, o.Name, o.Address, o.City}
}

func (o *Site) UpdateValues() []interface{} {
	return []interface{}{o.Modified, o.Postal, o.Country, o.Web, o.State, o.Phone, o.USR, o.Name, o.Address, o.City, o.STI}
}

func (o *Site) MemberPointers() []interface{} {
	return []interface{}{&o.STI, &o.Modified, &o.Postal, &o.Country, &o.Web, &o.State, &o.Phone, &o.USR, &o.Name, &o.Address, &o.City}
}

func (o *Site) Key() int64 {
	return o.STI
}

func (o *Site) SetID(id int64) {
	o.STI = id
}

func (o *Site) TableName() string {
	return "sites"
}

func (o *Site) SelectFields() string {
	return "sti,ts,postal,country,web,state,phone,usr,name,address,city"
}

func (o *Site) InsertFields() string {
	return "sti,ts,postal,country,web,state,phone,usr,name,address,city"
}

func (o *Site) KeyField() string {
	return "sti"
}

func (o *Site) KeyName() string {
	return "STI"
}

func (o *Site) Names() []string {
	return []string{"Modified", "Postal", "Country", "Web", "State", "Phone", "USR", "Name", "Address", "City"}
}

func (o *Site) ModifiedBy(user int64, t time.Time) {
	o.USR = user
	o.Modified = t
}

//
// Tag DBObject generator
//
func (o Tag) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// Tag DBObject interface functions
//
func (o *Tag) InsertValues() []interface{} {
	return []interface{}{o.Name}
}

func (o *Tag) UpdateValues() []interface{} {
	return []interface{}{o.Name, o.TID}
}

func (o *Tag) MemberPointers() []interface{} {
	return []interface{}{&o.TID, &o.Name}
}

func (o *Tag) Key() int64 {
	return o.TID
}

func (o *Tag) SetID(id int64) {
	o.TID = id
}

func (o *Tag) TableName() string {
	return "tags"
}

func (o *Tag) SelectFields() string {
	return "tid,tag"
}

func (o *Tag) InsertFields() string {
	return "tid,tag"
}

func (o *Tag) KeyField() string {
	return "tid"
}

func (o *Tag) KeyName() string {
	return "TID"
}

func (o *Tag) Names() []string {
	return []string{"Name"}
}

func (o *Tag) ModifiedBy(user int64, t time.Time) {
}

//
// Rack DBObject generator
//
func (o Rack) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// Rack DBObject interface functions
//
func (o *Rack) InsertValues() []interface{} {
	return []interface{}{o.YPos, o.TS, o.USR, o.STI, o.RUs, o.Label, o.VendorID, o.XPos, o.Note}
}

func (o *Rack) UpdateValues() []interface{} {
	return []interface{}{o.YPos, o.TS, o.USR, o.STI, o.RUs, o.Label, o.VendorID, o.XPos, o.Note, o.RID}
}

func (o *Rack) MemberPointers() []interface{} {
	return []interface{}{&o.RID, &o.YPos, &o.TS, &o.USR, &o.STI, &o.RUs, &o.Label, &o.VendorID, &o.XPos, &o.Note}
}

func (o *Rack) Key() int64 {
	return o.RID
}

func (o *Rack) SetID(id int64) {
	o.RID = id
}

func (o *Rack) TableName() string {
	return "racks"
}

func (o *Rack) SelectFields() string {
	return "rid,y_pos,ts,usr,sti,rackunits,rack,vendor_id,x_pos,note"
}

func (o *Rack) InsertFields() string {
	return "rid,y_pos,ts,usr,sti,rackunits,rack,vendor_id,x_pos,note"
}

func (o *Rack) KeyField() string {
	return "rid"
}

func (o *Rack) KeyName() string {
	return "RID"
}

func (o *Rack) Names() []string {
	return []string{"YPos", "TS", "USR", "STI", "RUs", "Label", "VendorID", "XPos", "Note"}
}

func (o *Rack) ModifiedBy(user int64, t time.Time) {
}

//
// RackView DBObject generator
//
func (o RackView) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// RackView DBObject interface functions
//
func (o *RackView) InsertValues() []interface{} {
	return []interface{}{o.Note, o.USR, o.TS, o.RUs, o.Label, o.Site, o.YPos, o.STI, o.VendorID, o.XPos}
}

func (o *RackView) UpdateValues() []interface{} {
	return []interface{}{o.Note, o.USR, o.TS, o.RUs, o.Label, o.Site, o.YPos, o.STI, o.VendorID, o.XPos, o.RID}
}

func (o *RackView) MemberPointers() []interface{} {
	return []interface{}{&o.RID, &o.Note, &o.USR, &o.TS, &o.RUs, &o.Label, &o.Site, &o.YPos, &o.STI, &o.VendorID, &o.XPos}
}

func (o *RackView) Key() int64 {
	return o.RID
}

func (o *RackView) SetID(id int64) {
	o.RID = id
}

func (o *RackView) TableName() string {
	return "racks_view"
}

func (o *RackView) SelectFields() string {
	return "rid,note,usr,ts,rackunits,rack,site,y_pos,sti,vendor_id,x_pos"
}

func (o *RackView) InsertFields() string {
	return "rid,note,usr,ts,rackunits,rack,site,y_pos,sti,vendor_id,x_pos"
}

func (o *RackView) KeyField() string {
	return "rid"
}

func (o *RackView) KeyName() string {
	return "RID"
}

func (o *RackView) Names() []string {
	return []string{"Note", "USR", "TS", "RUs", "Label", "Site", "YPos", "STI", "VendorID", "XPos"}
}

func (o *RackView) ModifiedBy(user int64, t time.Time) {
}

//
// VM DBObject generator
//
func (o VM) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// VM DBObject interface functions
//
func (o *VM) InsertValues() []interface{} {
	return []interface{}{o.DID, o.Hostname, o.Profile, o.Note, o.USR, o.Modified}
}

func (o *VM) UpdateValues() []interface{} {
	return []interface{}{o.DID, o.Hostname, o.Profile, o.Note, o.USR, o.Modified, o.VMI}
}

func (o *VM) MemberPointers() []interface{} {
	return []interface{}{&o.VMI, &o.DID, &o.Hostname, &o.Profile, &o.Note, &o.USR, &o.Modified}
}

func (o *VM) Key() int64 {
	return o.VMI
}

func (o *VM) SetID(id int64) {
	o.VMI = id
}

func (o *VM) TableName() string {
	return "vms"
}

func (o *VM) SelectFields() string {
	return "vmi,did,hostname,profile,note,usr,ts"
}

func (o *VM) InsertFields() string {
	return "vmi,did,hostname,profile,note,usr,ts"
}

func (o *VM) KeyField() string {
	return "vmi"
}

func (o *VM) KeyName() string {
	return "VMI"
}

func (o *VM) Names() []string {
	return []string{"DID", "Hostname", "Profile", "Note", "USR", "Modified"}
}

func (o *VM) ModifiedBy(user int64, t time.Time) {
}

//
// VMView DBObject generator
//
func (o VMView) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// VMView DBObject interface functions
//
func (o *VMView) InsertValues() []interface{} {
	return []interface{}{o.RID, o.Rack, o.Site, o.Profile, o.DID, o.STI, o.Server, o.Hostname, o.Note, o.USR, o.Modified}
}

func (o *VMView) UpdateValues() []interface{} {
	return []interface{}{o.RID, o.Rack, o.Site, o.Profile, o.DID, o.STI, o.Server, o.Hostname, o.Note, o.USR, o.Modified, o.VMI}
}

func (o *VMView) MemberPointers() []interface{} {
	return []interface{}{&o.VMI, &o.RID, &o.Rack, &o.Site, &o.Profile, &o.DID, &o.STI, &o.Server, &o.Hostname, &o.Note, &o.USR, &o.Modified}
}

func (o *VMView) Key() int64 {
	return o.VMI
}

func (o *VMView) SetID(id int64) {
	o.VMI = id
}

func (o *VMView) TableName() string {
	return "vms_view"
}

func (o *VMView) SelectFields() string {
	return "vmi,rid,rack,site,profile,did,sti,server,hostname,note,usr,ts"
}

func (o *VMView) InsertFields() string {
	return "vmi,rid,rack,site,profile,did,sti,server,hostname,note,usr,ts"
}

func (o *VMView) KeyField() string {
	return "vmi"
}

func (o *VMView) KeyName() string {
	return "VMI"
}

func (o *VMView) Names() []string {
	return []string{"RID", "Rack", "Site", "Profile", "DID", "STI", "Server", "Hostname", "Note", "USR", "Modified"}
}

func (o *VMView) ModifiedBy(user int64, t time.Time) {
}

//
// Audit DBObject generator
//
func (o Audit) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// Audit DBObject interface functions
//
func (o *Audit) InsertValues() []interface{} {
	return []interface{}{o.IpmiIP, o.VMs, o.Hostname, o.FQDN, o.Eth0, o.Kernel, o.CPU, o.Mem, o.IP, o.Eth1, o.IpmiMac, o.Release, o.IPs, o.SN, o.Asset}
}

func (o *Audit) UpdateValues() []interface{} {
	return []interface{}{o.IpmiIP, o.VMs, o.Hostname, o.FQDN, o.Eth0, o.Kernel, o.CPU, o.Mem, o.IP, o.Eth1, o.IpmiMac, o.Release, o.IPs, o.SN, o.Asset}
}

func (o *Audit) MemberPointers() []interface{} {
	return []interface{}{&o.IpmiIP, &o.VMs, &o.Hostname, &o.FQDN, &o.Eth0, &o.Kernel, &o.CPU, &o.Mem, &o.IP, &o.Eth1, &o.IpmiMac, &o.Release, &o.IPs, &o.SN, &o.Asset}
}

func (o *Audit) Key() int64 {
	return 0
}

func (o *Audit) SetID(id int64) {
}

func (o *Audit) TableName() string {
	return "auditing"
}

func (o *Audit) SelectFields() string {
	return "ipmi_ip,vms,hostname,fqdn,eth0,kernel,cpu,mem,remote_addr,eth1,ipmi_mac,release,ips,sn,asset"
}

func (o *Audit) InsertFields() string {
	return "ipmi_ip,vms,hostname,fqdn,eth0,kernel,cpu,mem,remote_addr,eth1,ipmi_mac,release,ips,sn,asset"
}

func (o *Audit) KeyField() string {
	return ""
}

func (o *Audit) KeyName() string {
	return ""
}

func (o *Audit) Names() []string {
	return []string{"IpmiIP", "VMs", "Hostname", "FQDN", "Eth0", "Kernel", "CPU", "Mem", "IP", "Eth1", "IpmiMac", "Release", "IPs", "SN", "Asset"}
}

func (o *Audit) ModifiedBy(user int64, t time.Time) {
}

//
// PDU DBObject generator
//
func (o PDU) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// PDU DBObject interface functions
//
func (o *PDU) InsertValues() []interface{} {
	return []interface{}{o.IP, o.Netmask, o.Gateway, o.DNS, o.AssetTag, o.RID, o.Hostname}
}

func (o *PDU) UpdateValues() []interface{} {
	return []interface{}{o.IP, o.Netmask, o.Gateway, o.DNS, o.AssetTag, o.RID, o.Hostname, o.ID}
}

func (o *PDU) MemberPointers() []interface{} {
	return []interface{}{&o.ID, &o.IP, &o.Netmask, &o.Gateway, &o.DNS, &o.AssetTag, &o.RID, &o.Hostname}
}

func (o *PDU) Key() int64 {
	return o.ID
}

func (o *PDU) SetID(id int64) {
	o.ID = id
}

func (o *PDU) TableName() string {
	return "pdus"
}

func (o *PDU) SelectFields() string {
	return "id,ip_address,netmask,gateway,dns,asset_tag,rid,hostname"
}

func (o *PDU) InsertFields() string {
	return "id,ip_address,netmask,gateway,dns,asset_tag,rid,hostname"
}

func (o *PDU) KeyField() string {
	return "id"
}

func (o *PDU) KeyName() string {
	return "ID"
}

func (o *PDU) Names() []string {
	return []string{"IP", "Netmask", "Gateway", "DNS", "AssetTag", "RID", "Hostname"}
}

func (o *PDU) ModifiedBy(user int64, t time.Time) {
}

//
// Inventory DBObject generator
//
func (o Inventory) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// Inventory DBObject interface functions
//
func (o *Inventory) InsertValues() []interface{} {
	return []interface{}{o.Cents, o.Price, o.KID, o.Mfgr, o.PartNumber, o.PartType, o.Description, o.PTI, o.Qty, o.Site}
}

func (o *Inventory) UpdateValues() []interface{} {
	return []interface{}{o.Cents, o.Price, o.KID, o.Mfgr, o.PartNumber, o.PartType, o.Description, o.PTI, o.Qty, o.Site, o.STI}
}

func (o *Inventory) MemberPointers() []interface{} {
	return []interface{}{&o.STI, &o.Cents, &o.Price, &o.KID, &o.Mfgr, &o.PartNumber, &o.PartType, &o.Description, &o.PTI, &o.Qty, &o.Site}
}

func (o *Inventory) Key() int64 {
	return o.STI
}

func (o *Inventory) SetID(id int64) {
	o.STI = id
}

func (o *Inventory) TableName() string {
	return "inventory"
}

func (o *Inventory) SelectFields() string {
	return "sti,cents,price,kid,mfgr,part_no,part_type,description,pti,qty,site"
}

func (o *Inventory) InsertFields() string {
	return "sti,cents,price,kid,mfgr,part_no,part_type,description,pti,qty,site"
}

func (o *Inventory) KeyField() string {
	return "sti"
}

func (o *Inventory) KeyName() string {
	return "STI"
}

func (o *Inventory) Names() []string {
	return []string{"Cents", "Price", "KID", "Mfgr", "PartNumber", "PartType", "Description", "PTI", "Qty", "Site"}
}

func (o *Inventory) ModifiedBy(user int64, t time.Time) {
}

//
// Contract DBObject generator
//
func (o Contract) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// Contract DBObject interface functions
//
func (o *Contract) InsertValues() []interface{} {
	return []interface{}{o.VID, o.Policy, o.Phone}
}

func (o *Contract) UpdateValues() []interface{} {
	return []interface{}{o.VID, o.Policy, o.Phone, o.CID}
}

func (o *Contract) MemberPointers() []interface{} {
	return []interface{}{&o.CID, &o.VID, &o.Policy, &o.Phone}
}

func (o *Contract) Key() int64 {
	return o.CID
}

func (o *Contract) SetID(id int64) {
	o.CID = id
}

func (o *Contract) TableName() string {
	return "contracts"
}

func (o *Contract) SelectFields() string {
	return "cid,vid,policy,phone"
}

func (o *Contract) InsertFields() string {
	return "cid,vid,policy,phone"
}

func (o *Contract) KeyField() string {
	return "cid"
}

func (o *Contract) KeyName() string {
	return "CID"
}

func (o *Contract) Names() []string {
	return []string{"VID", "Policy", "Phone"}
}

func (o *Contract) ModifiedBy(user int64, t time.Time) {
}

//
// DeviceType DBObject generator
//
func (o DeviceType) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// DeviceType DBObject interface functions
//
func (o *DeviceType) InsertValues() []interface{} {
	return []interface{}{o.Name}
}

func (o *DeviceType) UpdateValues() []interface{} {
	return []interface{}{o.Name, o.DTI}
}

func (o *DeviceType) MemberPointers() []interface{} {
	return []interface{}{&o.DTI, &o.Name}
}

func (o *DeviceType) Key() int64 {
	return o.DTI
}

func (o *DeviceType) SetID(id int64) {
	o.DTI = id
}

func (o *DeviceType) TableName() string {
	return "device_types"
}

func (o *DeviceType) SelectFields() string {
	return "dti,name"
}

func (o *DeviceType) InsertFields() string {
	return "dti,name"
}

func (o *DeviceType) KeyField() string {
	return "dti"
}

func (o *DeviceType) KeyName() string {
	return "DTI"
}

func (o *DeviceType) Names() []string {
	return []string{"Name"}
}

func (o *DeviceType) ModifiedBy(user int64, t time.Time) {
}

//
// Device DBObject generator
//
func (o Device) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// Device DBObject interface functions
//
func (o *Device) InsertValues() []interface{} {
	return []interface{}{o.DTI, o.TID, o.RU, o.Hostname, o.SerialNo, o.USR, o.KID, o.Alias, o.AssetTag, o.Assigned, o.Profile, o.Note, o.Modified, o.RID, o.Height}
}

func (o *Device) UpdateValues() []interface{} {
	return []interface{}{o.DTI, o.TID, o.RU, o.Hostname, o.SerialNo, o.USR, o.KID, o.Alias, o.AssetTag, o.Assigned, o.Profile, o.Note, o.Modified, o.RID, o.Height, o.DID}
}

func (o *Device) MemberPointers() []interface{} {
	return []interface{}{&o.DID, &o.DTI, &o.TID, &o.RU, &o.Hostname, &o.SerialNo, &o.USR, &o.KID, &o.Alias, &o.AssetTag, &o.Assigned, &o.Profile, &o.Note, &o.Modified, &o.RID, &o.Height}
}

func (o *Device) Key() int64 {
	return o.DID
}

func (o *Device) SetID(id int64) {
	o.DID = id
}

func (o *Device) TableName() string {
	return "devices"
}

func (o *Device) SelectFields() string {
	return "did,dti,tid,ru,hostname,sn,usr,kid,alias,asset_tag,assigned,profile,note,ts,rid,height"
}

func (o *Device) InsertFields() string {
	return "did,dti,tid,ru,hostname,sn,usr,kid,alias,asset_tag,assigned,profile,note,ts,rid,height"
}

func (o *Device) KeyField() string {
	return "did"
}

func (o *Device) KeyName() string {
	return "DID"
}

func (o *Device) Names() []string {
	return []string{"DTI", "TID", "RU", "Hostname", "SerialNo", "USR", "KID", "Alias", "AssetTag", "Assigned", "Profile", "Note", "Modified", "RID", "Height"}
}

func (o *Device) ModifiedBy(user int64, t time.Time) {
}

//
// DeviceView DBObject generator
//
func (o DeviceView) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// DeviceView DBObject interface functions
//
func (o *DeviceView) InsertValues() []interface{} {
	return []interface{}{o.AssetTag, o.USR, o.STI, o.Hostname, o.Alias, o.Site, o.DTI, o.RID, o.RU, o.Height, o.Profile, o.KID, o.Rack, o.SerialNo, o.Assigned, o.Note, o.DevType, o.Tag, o.Modified, o.TID}
}

func (o *DeviceView) UpdateValues() []interface{} {
	return []interface{}{o.AssetTag, o.USR, o.STI, o.Hostname, o.Alias, o.Site, o.DTI, o.RID, o.RU, o.Height, o.Profile, o.KID, o.Rack, o.SerialNo, o.Assigned, o.Note, o.DevType, o.Tag, o.Modified, o.TID, o.DID}
}

func (o *DeviceView) MemberPointers() []interface{} {
	return []interface{}{&o.DID, &o.AssetTag, &o.USR, &o.STI, &o.Hostname, &o.Alias, &o.Site, &o.DTI, &o.RID, &o.RU, &o.Height, &o.Profile, &o.KID, &o.Rack, &o.SerialNo, &o.Assigned, &o.Note, &o.DevType, &o.Tag, &o.Modified, &o.TID}
}

func (o *DeviceView) Key() int64 {
	return o.DID
}

func (o *DeviceView) SetID(id int64) {
	o.DID = id
}

func (o *DeviceView) TableName() string {
	return "devices_view"
}

func (o *DeviceView) SelectFields() string {
	return "did,asset_tag,usr,sti,hostname,alias,site,dti,rid,ru,height,profile,kid,rack,sn,assigned,note,devtype,tag,ts,tid"
}

func (o *DeviceView) InsertFields() string {
	return "did,asset_tag,usr,sti,hostname,alias,site,dti,rid,ru,height,profile,kid,rack,sn,assigned,note,devtype,tag,ts,tid"
}

func (o *DeviceView) KeyField() string {
	return "did"
}

func (o *DeviceView) KeyName() string {
	return "DID"
}

func (o *DeviceView) Names() []string {
	return []string{"AssetTag", "USR", "STI", "Hostname", "Alias", "Site", "DTI", "RID", "RU", "Height", "Profile", "KID", "Rack", "SerialNo", "Assigned", "Note", "DevType", "Tag", "Modified", "TID"}
}

func (o *DeviceView) ModifiedBy(user int64, t time.Time) {
}

//
// DeviceIPs DBObject generator
//
func (o DeviceIPs) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// DeviceIPs DBObject interface functions
//
func (o *DeviceIPs) InsertValues() []interface{} {
	return []interface{}{o.KID, o.TID, o.RU, o.Alias, o.Profile, o.AssetTag, o.Tag, o.Note, o.DevType, o.STI, o.Rack, o.Height, o.Hostname, o.Mgmt, o.SerialNo, o.Site, o.RID, o.DTI, o.Assigned, o.IPs, o.USR, o.Modified}
}

func (o *DeviceIPs) UpdateValues() []interface{} {
	return []interface{}{o.KID, o.TID, o.RU, o.Alias, o.Profile, o.AssetTag, o.Tag, o.Note, o.DevType, o.STI, o.Rack, o.Height, o.Hostname, o.Mgmt, o.SerialNo, o.Site, o.RID, o.DTI, o.Assigned, o.IPs, o.USR, o.Modified, o.DID}
}

func (o *DeviceIPs) MemberPointers() []interface{} {
	return []interface{}{&o.DID, &o.KID, &o.TID, &o.RU, &o.Alias, &o.Profile, &o.AssetTag, &o.Tag, &o.Note, &o.DevType, &o.STI, &o.Rack, &o.Height, &o.Hostname, &o.Mgmt, &o.SerialNo, &o.Site, &o.RID, &o.DTI, &o.Assigned, &o.IPs, &o.USR, &o.Modified}
}

func (o *DeviceIPs) Key() int64 {
	return o.DID
}

func (o *DeviceIPs) SetID(id int64) {
	o.DID = id
}

func (o *DeviceIPs) TableName() string {
	return "devices_list"
}

func (o *DeviceIPs) SelectFields() string {
	return "did,kid,tid,ru,alias,profile,asset_tag,tag,note,devtype,sti,rack,height,hostname,mgmt,sn,site,rid,dti,assigned,ips,usr,ts"
}

func (o *DeviceIPs) InsertFields() string {
	return "did,kid,tid,ru,alias,profile,asset_tag,tag,note,devtype,sti,rack,height,hostname,mgmt,sn,site,rid,dti,assigned,ips,usr,ts"
}

func (o *DeviceIPs) KeyField() string {
	return "did"
}

func (o *DeviceIPs) KeyName() string {
	return "DID"
}

func (o *DeviceIPs) Names() []string {
	return []string{"KID", "TID", "RU", "Alias", "Profile", "AssetTag", "Tag", "Note", "DevType", "STI", "Rack", "Height", "Hostname", "Mgmt", "SerialNo", "Site", "RID", "DTI", "Assigned", "IPs", "USR", "Modified"}
}

func (o *DeviceIPs) ModifiedBy(user int64, t time.Time) {
}

//
// DeviceAdjust DBObject generator
//
func (o DeviceAdjust) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// DeviceAdjust DBObject interface functions
//
func (o *DeviceAdjust) InsertValues() []interface{} {
	return []interface{}{o.RU, o.Height, o.RID}
}

func (o *DeviceAdjust) UpdateValues() []interface{} {
	return []interface{}{o.RU, o.Height, o.RID, o.DID}
}

func (o *DeviceAdjust) MemberPointers() []interface{} {
	return []interface{}{&o.DID, &o.RU, &o.Height, &o.RID}
}

func (o *DeviceAdjust) Key() int64 {
	return o.DID
}

func (o *DeviceAdjust) SetID(id int64) {
	o.DID = id
}

func (o *DeviceAdjust) TableName() string {
	return "devices_adjust"
}

func (o *DeviceAdjust) SelectFields() string {
	return "did,ru,height,rid"
}

func (o *DeviceAdjust) InsertFields() string {
	return "did,ru,height,rid"
}

func (o *DeviceAdjust) KeyField() string {
	return "did"
}

func (o *DeviceAdjust) KeyName() string {
	return "DID"
}

func (o *DeviceAdjust) Names() []string {
	return []string{"RU", "Height", "RID"}
}

func (o *DeviceAdjust) ModifiedBy(user int64, t time.Time) {
}

//
// IFace DBObject generator
//
func (o IFace) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// IFace DBObject interface functions
//
func (o *IFace) InsertValues() []interface{} {
	return []interface{}{o.SwitchPort, o.DID, o.Mgmt, o.Port, o.MAC, o.CableTag}
}

func (o *IFace) UpdateValues() []interface{} {
	return []interface{}{o.SwitchPort, o.DID, o.Mgmt, o.Port, o.MAC, o.CableTag, o.IFD}
}

func (o *IFace) MemberPointers() []interface{} {
	return []interface{}{&o.IFD, &o.SwitchPort, &o.DID, &o.Mgmt, &o.Port, &o.MAC, &o.CableTag}
}

func (o *IFace) Key() int64 {
	return o.IFD
}

func (o *IFace) SetID(id int64) {
	o.IFD = id
}

func (o *IFace) TableName() string {
	return "interfaces"
}

func (o *IFace) SelectFields() string {
	return "ifd,switch_port,did,mgmt,port,mac,cable_tag"
}

func (o *IFace) InsertFields() string {
	return "ifd,switch_port,did,mgmt,port,mac,cable_tag"
}

func (o *IFace) KeyField() string {
	return "ifd"
}

func (o *IFace) KeyName() string {
	return "IFD"
}

func (o *IFace) Names() []string {
	return []string{"SwitchPort", "DID", "Mgmt", "Port", "MAC", "CableTag"}
}

func (o *IFace) ModifiedBy(user int64, t time.Time) {
}

//
// IFaceView DBObject generator
//
func (o IFaceView) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// IFaceView DBObject interface functions
//
func (o *IFaceView) InsertValues() []interface{} {
	return []interface{}{o.IP, o.IPType, o.SwitchPort, o.IID, o.IPT, o.Mgmt, o.Port, o.MAC, o.CableTag, o.DID, o.IP32}
}

func (o *IFaceView) UpdateValues() []interface{} {
	return []interface{}{o.IP, o.IPType, o.SwitchPort, o.IID, o.IPT, o.Mgmt, o.Port, o.MAC, o.CableTag, o.DID, o.IP32, o.IFD}
}

func (o *IFaceView) MemberPointers() []interface{} {
	return []interface{}{&o.IFD, &o.IP, &o.IPType, &o.SwitchPort, &o.IID, &o.IPT, &o.Mgmt, &o.Port, &o.MAC, &o.CableTag, &o.DID, &o.IP32}
}

func (o *IFaceView) Key() int64 {
	return o.IFD
}

func (o *IFaceView) SetID(id int64) {
	o.IFD = id
}

func (o *IFaceView) TableName() string {
	return "interfaces_view"
}

func (o *IFaceView) SelectFields() string {
	return "ifd,ipv4,iptype,switch_port,iid,ipt,mgmt,port,mac,cable_tag,did,ip32"
}

func (o *IFaceView) InsertFields() string {
	return "ifd,ipv4,iptype,switch_port,iid,ipt,mgmt,port,mac,cable_tag,did,ip32"
}

func (o *IFaceView) KeyField() string {
	return "ifd"
}

func (o *IFaceView) KeyName() string {
	return "IFD"
}

func (o *IFaceView) Names() []string {
	return []string{"IP", "IPType", "SwitchPort", "IID", "IPT", "Mgmt", "Port", "MAC", "CableTag", "DID", "IP32"}
}

func (o *IFaceView) ModifiedBy(user int64, t time.Time) {
}

//
// IPAddr DBObject generator
//
func (o IPAddr) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// IPAddr DBObject interface functions
//
func (o *IPAddr) InsertValues() []interface{} {
	return []interface{}{o.VLI, o.IPT, o.IP32, o.IPv4, o.Note, o.IFD, o.VMI}
}

func (o *IPAddr) UpdateValues() []interface{} {
	return []interface{}{o.VLI, o.IPT, o.IP32, o.IPv4, o.Note, o.IFD, o.VMI, o.IID}
}

func (o *IPAddr) MemberPointers() []interface{} {
	return []interface{}{&o.IID, &o.VLI, &o.IPT, &o.IP32, &o.IPv4, &o.Note, &o.IFD, &o.VMI}
}

func (o *IPAddr) Key() int64 {
	return o.IID
}

func (o *IPAddr) SetID(id int64) {
	o.IID = id
}

func (o *IPAddr) TableName() string {
	return "ips"
}

func (o *IPAddr) SelectFields() string {
	return "iid,vli,ipt,ip32,ipv4,note,ifd,vmi"
}

func (o *IPAddr) InsertFields() string {
	return "iid,vli,ipt,ip32,ipv4,note,ifd,vmi"
}

func (o *IPAddr) KeyField() string {
	return "iid"
}

func (o *IPAddr) KeyName() string {
	return "IID"
}

func (o *IPAddr) Names() []string {
	return []string{"VLI", "IPT", "IP32", "IPv4", "Note", "IFD", "VMI"}
}

func (o *IPAddr) ModifiedBy(user int64, t time.Time) {
}

//
// IPsUsed DBObject generator
//
func (o IPsUsed) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// IPsUsed DBObject interface functions
//
func (o *IPsUsed) InsertValues() []interface{} {
	return []interface{}{o.Note, o.RID, o.IPT, o.Type, o.Host, o.Hostname, o.ID, o.STI, o.Site, o.Rack, o.IP}
}

func (o *IPsUsed) UpdateValues() []interface{} {
	return []interface{}{o.Note, o.RID, o.IPT, o.Type, o.Host, o.Hostname, o.ID, o.STI, o.Site, o.Rack, o.IP}
}

func (o *IPsUsed) MemberPointers() []interface{} {
	return []interface{}{&o.Note, &o.RID, &o.IPT, &o.Type, &o.Host, &o.Hostname, &o.ID, &o.STI, &o.Site, &o.Rack, &o.IP}
}

func (o *IPsUsed) Key() int64 {
	return 0
}

func (o *IPsUsed) SetID(id int64) {
}

func (o *IPsUsed) TableName() string {
	return "ips_list"
}

func (o *IPsUsed) SelectFields() string {
	return "note,rid,ipt,iptype,host,hostname,id,sti,site,rack,ip"
}

func (o *IPsUsed) InsertFields() string {
	return "note,rid,ipt,iptype,host,hostname,id,sti,site,rack,ip"
}

func (o *IPsUsed) KeyField() string {
	return ""
}

func (o *IPsUsed) KeyName() string {
	return ""
}

func (o *IPsUsed) Names() []string {
	return []string{"Note", "RID", "IPT", "Type", "Host", "Hostname", "ID", "STI", "Site", "Rack", "IP"}
}

func (o *IPsUsed) ModifiedBy(user int64, t time.Time) {
}

//
// Provider DBObject generator
//
func (o Provider) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// Provider DBObject interface functions
//
func (o *Provider) InsertValues() []interface{} {
	return []interface{}{o.Name, o.Contact, o.Phone, o.EMail, o.URL, o.Note}
}

func (o *Provider) UpdateValues() []interface{} {
	return []interface{}{o.Name, o.Contact, o.Phone, o.EMail, o.URL, o.Note, o.PRI}
}

func (o *Provider) MemberPointers() []interface{} {
	return []interface{}{&o.PRI, &o.Name, &o.Contact, &o.Phone, &o.EMail, &o.URL, &o.Note}
}

func (o *Provider) Key() int64 {
	return o.PRI
}

func (o *Provider) SetID(id int64) {
	o.PRI = id
}

func (o *Provider) TableName() string {
	return "providers"
}

func (o *Provider) SelectFields() string {
	return "pri,name,provider,a_side_xcon,a_side_handoff,z_side_xcon,note"
}

func (o *Provider) InsertFields() string {
	return "pri,name,provider,a_side_xcon,a_side_handoff,z_side_xcon,note"
}

func (o *Provider) KeyField() string {
	return "pri"
}

func (o *Provider) KeyName() string {
	return "PRI"
}

func (o *Provider) Names() []string {
	return []string{"Name", "Contact", "Phone", "EMail", "URL", "Note"}
}

func (o *Provider) ModifiedBy(user int64, t time.Time) {
}

//
// Circuit DBObject generator
//
func (o Circuit) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// Circuit DBObject interface functions
//
func (o *Circuit) InsertValues() []interface{} {
	return []interface{}{o.ASideXConn, o.ASideHandoff, o.ZSideXConn, o.ZSideHandoff, o.Note, o.STI, o.PRI, o.CircuitID}
}

func (o *Circuit) UpdateValues() []interface{} {
	return []interface{}{o.ASideXConn, o.ASideHandoff, o.ZSideXConn, o.ZSideHandoff, o.Note, o.STI, o.PRI, o.CircuitID, o.CID}
}

func (o *Circuit) MemberPointers() []interface{} {
	return []interface{}{&o.CID, &o.ASideXConn, &o.ASideHandoff, &o.ZSideXConn, &o.ZSideHandoff, &o.Note, &o.STI, &o.PRI, &o.CircuitID}
}

func (o *Circuit) Key() int64 {
	return o.CID
}

func (o *Circuit) SetID(id int64) {
	o.CID = id
}

func (o *Circuit) TableName() string {
	return "circuits"
}

func (o *Circuit) SelectFields() string {
	return "cid,a_side_xcon,a_side_handoff,z_side_xcon,z_side_handoff,note,site,pri,circuit_id"
}

func (o *Circuit) InsertFields() string {
	return "cid,a_side_xcon,a_side_handoff,z_side_xcon,z_side_handoff,note,site,pri,circuit_id"
}

func (o *Circuit) KeyField() string {
	return "cid"
}

func (o *Circuit) KeyName() string {
	return "CID"
}

func (o *Circuit) Names() []string {
	return []string{"ASideXConn", "ASideHandoff", "ZSideXConn", "ZSideHandoff", "Note", "STI", "PRI", "CircuitID"}
}

func (o *Circuit) ModifiedBy(user int64, t time.Time) {
}

//
// CircuitView DBObject generator
//
func (o CircuitView) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// CircuitView DBObject interface functions
//
func (o *CircuitView) InsertValues() []interface{} {
	return []interface{}{o.CircuitID, o.ASideXConn, o.ZSideXConn, o.ZSideHandoff, o.ASideHandoff, o.Note, o.STI, o.PRI, o.Site, o.Provider}
}

func (o *CircuitView) UpdateValues() []interface{} {
	return []interface{}{o.CircuitID, o.ASideXConn, o.ZSideXConn, o.ZSideHandoff, o.ASideHandoff, o.Note, o.STI, o.PRI, o.Site, o.Provider, o.CID}
}

func (o *CircuitView) MemberPointers() []interface{} {
	return []interface{}{&o.CID, &o.CircuitID, &o.ASideXConn, &o.ZSideXConn, &o.ZSideHandoff, &o.ASideHandoff, &o.Note, &o.STI, &o.PRI, &o.Site, &o.Provider}
}

func (o *CircuitView) Key() int64 {
	return o.CID
}

func (o *CircuitView) SetID(id int64) {
	o.CID = id
}

func (o *CircuitView) TableName() string {
	return "circuits"
}

func (o *CircuitView) SelectFields() string {
	return "cid,circuit_id,a_side_xcon,z_side_xcon,z_side_handoff,a_side_handoff,note,site,pri,site,provider"
}

func (o *CircuitView) InsertFields() string {
	return "cid,circuit_id,a_side_xcon,z_side_xcon,z_side_handoff,a_side_handoff,note,site,pri,site,provider"
}

func (o *CircuitView) KeyField() string {
	return "cid"
}

func (o *CircuitView) KeyName() string {
	return "CID"
}

func (o *CircuitView) Names() []string {
	return []string{"CircuitID", "ASideXConn", "ZSideXConn", "ZSideHandoff", "ASideHandoff", "Note", "STI", "PRI", "Site", "Provider"}
}

func (o *CircuitView) ModifiedBy(user int64, t time.Time) {
}

//
// SubCircuit DBObject generator
//
func (o SubCircuit) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// SubCircuit DBObject interface functions
//
func (o *SubCircuit) InsertValues() []interface{} {
	return []interface{}{o.CID, o.SubID, o.Note}
}

func (o *SubCircuit) UpdateValues() []interface{} {
	return []interface{}{o.CID, o.SubID, o.Note, o.SCI}
}

func (o *SubCircuit) MemberPointers() []interface{} {
	return []interface{}{&o.SCI, &o.CID, &o.SubID, &o.Note}
}

func (o *SubCircuit) Key() int64 {
	return o.SCI
}

func (o *SubCircuit) SetID(id int64) {
	o.SCI = id
}

func (o *SubCircuit) TableName() string {
	return "sub_circuits"
}

func (o *SubCircuit) SelectFields() string {
	return "sci,cid,sub_circuit_id,note"
}

func (o *SubCircuit) InsertFields() string {
	return "sci,cid,sub_circuit_id,note"
}

func (o *SubCircuit) KeyField() string {
	return "sci"
}

func (o *SubCircuit) KeyName() string {
	return "SCI"
}

func (o *SubCircuit) Names() []string {
	return []string{"CID", "SubID", "Note"}
}

func (o *SubCircuit) ModifiedBy(user int64, t time.Time) {
}

//
// CircuitList DBObject generator
//
func (o CircuitList) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// CircuitList DBObject interface functions
//
func (o *CircuitList) InsertValues() []interface{} {
	return []interface{}{o.SubNote, o.PRI, o.Provider, o.CircuitID, o.ZSideHandoff, o.Note, o.ZSideXConn, o.STI, o.Site, o.SubID, o.ASideXConn, o.ASideHandoff}
}

func (o *CircuitList) UpdateValues() []interface{} {
	return []interface{}{o.SubNote, o.PRI, o.Provider, o.CircuitID, o.ZSideHandoff, o.Note, o.ZSideXConn, o.STI, o.Site, o.SubID, o.ASideXConn, o.ASideHandoff, o.CID}
}

func (o *CircuitList) MemberPointers() []interface{} {
	return []interface{}{&o.CID, &o.SubNote, &o.PRI, &o.Provider, &o.CircuitID, &o.ZSideHandoff, &o.Note, &o.ZSideXConn, &o.STI, &o.Site, &o.SubID, &o.ASideXConn, &o.ASideHandoff}
}

func (o *CircuitList) Key() int64 {
	return o.CID
}

func (o *CircuitList) SetID(id int64) {
	o.CID = id
}

func (o *CircuitList) TableName() string {
	return "circuits"
}

func (o *CircuitList) SelectFields() string {
	return "cid,sub_note,pri,provider,circuit_id,z_side_handoff,note,z_side_xcon,site,site,sub_circuit_id,a_side_xcon,a_side_handoff"
}

func (o *CircuitList) InsertFields() string {
	return "cid,sub_note,pri,provider,circuit_id,z_side_handoff,note,z_side_xcon,site,site,sub_circuit_id,a_side_xcon,a_side_handoff"
}

func (o *CircuitList) KeyField() string {
	return "cid"
}

func (o *CircuitList) KeyName() string {
	return "CID"
}

func (o *CircuitList) Names() []string {
	return []string{"SubNote", "PRI", "Provider", "CircuitID", "ZSideHandoff", "Note", "ZSideXConn", "STI", "Site", "SubID", "ASideXConn", "ASideHandoff"}
}

func (o *CircuitList) ModifiedBy(user int64, t time.Time) {
}

//
// VProfile DBObject generator
//
func (o VProfile) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// VProfile DBObject interface functions
//
func (o *VProfile) InsertValues() []interface{} {
	return []interface{}{o.Name}
}

func (o *VProfile) UpdateValues() []interface{} {
	return []interface{}{o.Name, o.VPID}
}

func (o *VProfile) MemberPointers() []interface{} {
	return []interface{}{&o.VPID, &o.Name}
}

func (o *VProfile) Key() int64 {
	return o.VPID
}

func (o *VProfile) SetID(id int64) {
	o.VPID = id
}

func (o *VProfile) TableName() string {
	return "vlan_profiles"
}

func (o *VProfile) SelectFields() string {
	return "vpid,name"
}

func (o *VProfile) InsertFields() string {
	return "vpid,name"
}

func (o *VProfile) KeyField() string {
	return "vpid"
}

func (o *VProfile) KeyName() string {
	return "VPID"
}

func (o *VProfile) Names() []string {
	return []string{"Name"}
}

func (o *VProfile) ModifiedBy(user int64, t time.Time) {
}

//
// VLAN DBObject generator
//
func (o VLAN) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// VLAN DBObject interface functions
//
func (o *VLAN) InsertValues() []interface{} {
	return []interface{}{o.STI, o.Route, o.Netmask, o.USR, o.Modified, o.Name, o.Profile, o.Gateway, o.Note}
}

func (o *VLAN) UpdateValues() []interface{} {
	return []interface{}{o.STI, o.Route, o.Netmask, o.USR, o.Modified, o.Name, o.Profile, o.Gateway, o.Note, o.VLI}
}

func (o *VLAN) MemberPointers() []interface{} {
	return []interface{}{&o.VLI, &o.STI, &o.Route, &o.Netmask, &o.USR, &o.Modified, &o.Name, &o.Profile, &o.Gateway, &o.Note}
}

func (o *VLAN) Key() int64 {
	return o.VLI
}

func (o *VLAN) SetID(id int64) {
	o.VLI = id
}

func (o *VLAN) TableName() string {
	return "vlans"
}

func (o *VLAN) SelectFields() string {
	return "vli,sti,route,netmask,usr,ts,name,profile,gateway,note"
}

func (o *VLAN) InsertFields() string {
	return "vli,sti,route,netmask,usr,ts,name,profile,gateway,note"
}

func (o *VLAN) KeyField() string {
	return "vli"
}

func (o *VLAN) KeyName() string {
	return "VLI"
}

func (o *VLAN) Names() []string {
	return []string{"STI", "Route", "Netmask", "USR", "Modified", "Name", "Profile", "Gateway", "Note"}
}

func (o *VLAN) ModifiedBy(user int64, t time.Time) {
	o.USR = user
	o.Modified = t
}

//
// VLANView DBObject generator
//
func (o VLANView) NewObj() interface{} {
	ditto := o
	return &ditto
}

//
// VLANView DBObject interface functions
//
func (o *VLANView) InsertValues() []interface{} {
	return []interface{}{o.STI, o.Profile, o.Route, o.Netmask, o.Note, o.USR, o.Name, o.Site, o.Gateway, o.Modified}
}

func (o *VLANView) UpdateValues() []interface{} {
	return []interface{}{o.STI, o.Profile, o.Route, o.Netmask, o.Note, o.USR, o.Name, o.Site, o.Gateway, o.Modified, o.VLI}
}

func (o *VLANView) MemberPointers() []interface{} {
	return []interface{}{&o.VLI, &o.STI, &o.Profile, &o.Route, &o.Netmask, &o.Note, &o.USR, &o.Name, &o.Site, &o.Gateway, &o.Modified}
}

func (o *VLANView) Key() int64 {
	return o.VLI
}

func (o *VLANView) SetID(id int64) {
	o.VLI = id
}

func (o *VLANView) TableName() string {
	return "vlans_view"
}

func (o *VLANView) SelectFields() string {
	return "vli,sti,profile,route,netmask,note,usr,name,site,gateway,ts"
}

func (o *VLANView) InsertFields() string {
	return "vli,sti,profile,route,netmask,note,usr,name,site,gateway,ts"
}

func (o *VLANView) KeyField() string {
	return "vli"
}

func (o *VLANView) KeyName() string {
	return "VLI"
}

func (o *VLANView) Names() []string {
	return []string{"STI", "Profile", "Route", "Netmask", "Note", "USR", "Name", "Site", "Gateway", "Modified"}
}

func (o *VLANView) ModifiedBy(user int64, t time.Time) {
	o.USR = user
	o.Modified = t
}
